// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.6
// source: service.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\x05dropz\x1a\vgopro.proto\x1a\vvideo.proto\x1a\n" +
	"logs.proto\x1a\fconfig.proto\x1a\fcommon.proto2\xeb\v\n" +
	"\fDropzService\x12_\n" +
	"\x14GetDiscoveredCameras\x12\".dropz.GetDiscoveredCamerasRequest\x1a#.dropz.GetDiscoveredCamerasResponse\x12c\n" +
	"\x16WatchDiscoveredCameras\x12\".dropz.GetDiscoveredCamerasRequest\x1a#.dropz.GetDiscoveredCamerasResponse0\x01\x12V\n" +
	"\x11GetManagedCameras\x12\x1f.dropz.GetManagedCamerasRequest\x1a .dropz.GetManagedCamerasResponse\x12Z\n" +
	"\x13WatchManagedCameras\x12\x1f.dropz.GetManagedCamerasRequest\x1a .dropz.GetManagedCamerasResponse0\x01\x12G\n" +
	"\fManageCamera\x12\x1a.dropz.ManageCameraRequest\x1a\x1b.dropz.ManageCameraResponse\x12M\n" +
	"\x0eUnmanageCamera\x12\x1c.dropz.UnmanageCameraRequest\x1a\x1d.dropz.UnmanageCameraResponse\x12A\n" +
	"\n" +
	"PairCamera\x12\x18.dropz.PairCameraRequest\x1a\x19.dropz.PairCameraResponse\x12G\n" +
	"\fGetSyncQueue\x12\x1a.dropz.GetSyncQueueRequest\x1a\x1b.dropz.GetSyncQueueResponse\x12K\n" +
	"\x0eWatchSyncQueue\x12\x1a.dropz.GetSyncQueueRequest\x1a\x1b.dropz.GetSyncQueueResponse0\x01\x12>\n" +
	"\tForceSync\x12\x17.dropz.ForceSyncRequest\x1a\x18.dropz.ForceSyncResponse\x12>\n" +
	"\tGetGroups\x12\x17.dropz.GetGroupsRequest\x1a\x18.dropz.GetGroupsResponse\x126\n" +
	"\vCreateGroup\x12\x19.dropz.CreateGroupRequest\x1a\f.dropz.Group\x126\n" +
	"\vUpdateGroup\x12\x19.dropz.UpdateGroupRequest\x1a\f.dropz.Group\x12B\n" +
	"\vDeleteGroup\x12\x19.dropz.DeleteGroupRequest\x1a\x18.dropz.OperationResponse\x12>\n" +
	"\tGetVideos\x12\x17.dropz.GetVideosRequest\x1a\x18.dropz.GetVideosResponse\x12>\n" +
	"\tGetConfig\x12\x17.dropz.GetConfigRequest\x1a\x18.dropz.GetConfigResponse\x12G\n" +
	"\fUpdateConfig\x12\x1a.dropz.UpdateConfigRequest\x1a\x1b.dropz.UpdateConfigResponse\x12A\n" +
	"\n" +
	"GetSetting\x12\x18.dropz.GetSettingRequest\x1a\x19.dropz.GetSettingResponse\x12;\n" +
	"\rUpdateSetting\x12\x1b.dropz.UpdateSettingRequest\x1a\r.dropz.Config\x129\n" +
	"\fResetSetting\x12\x1a.dropz.ResetSettingRequest\x1a\r.dropz.Config\x128\n" +
	"\aGetLogs\x12\x15.dropz.GetLogsRequest\x1a\x16.dropz.GetLogsResponseB%Z#github.com/dropz/dropz/pkg/protocolb\x06proto3"

var file_service_proto_goTypes = []any{
	(*GetDiscoveredCamerasRequest)(nil),  // 0: dropz.GetDiscoveredCamerasRequest
	(*GetManagedCamerasRequest)(nil),     // 1: dropz.GetManagedCamerasRequest
	(*ManageCameraRequest)(nil),          // 2: dropz.ManageCameraRequest
	(*UnmanageCameraRequest)(nil),        // 3: dropz.UnmanageCameraRequest
	(*PairCameraRequest)(nil),            // 4: dropz.PairCameraRequest
	(*GetSyncQueueRequest)(nil),          // 5: dropz.GetSyncQueueRequest
	(*ForceSyncRequest)(nil),             // 6: dropz.ForceSyncRequest
	(*GetGroupsRequest)(nil),             // 7: dropz.GetGroupsRequest
	(*CreateGroupRequest)(nil),           // 8: dropz.CreateGroupRequest
	(*UpdateGroupRequest)(nil),           // 9: dropz.UpdateGroupRequest
	(*DeleteGroupRequest)(nil),           // 10: dropz.DeleteGroupRequest
	(*GetVideosRequest)(nil),             // 11: dropz.GetVideosRequest
	(*GetConfigRequest)(nil),             // 12: dropz.GetConfigRequest
	(*UpdateConfigRequest)(nil),          // 13: dropz.UpdateConfigRequest
	(*GetSettingRequest)(nil),            // 14: dropz.GetSettingRequest
	(*UpdateSettingRequest)(nil),         // 15: dropz.UpdateSettingRequest
	(*ResetSettingRequest)(nil),          // 16: dropz.ResetSettingRequest
	(*GetLogsRequest)(nil),               // 17: dropz.GetLogsRequest
	(*GetDiscoveredCamerasResponse)(nil), // 18: dropz.GetDiscoveredCamerasResponse
	(*GetManagedCamerasResponse)(nil),    // 19: dropz.GetManagedCamerasResponse
	(*ManageCameraResponse)(nil),         // 20: dropz.ManageCameraResponse
	(*UnmanageCameraResponse)(nil),       // 21: dropz.UnmanageCameraResponse
	(*PairCameraResponse)(nil),           // 22: dropz.PairCameraResponse
	(*GetSyncQueueResponse)(nil),         // 23: dropz.GetSyncQueueResponse
	(*ForceSyncResponse)(nil),            // 24: dropz.ForceSyncResponse
	(*GetGroupsResponse)(nil),            // 25: dropz.GetGroupsResponse
	(*Group)(nil),                        // 26: dropz.Group
	(*OperationResponse)(nil),            // 27: dropz.OperationResponse
	(*GetVideosResponse)(nil),            // 28: dropz.GetVideosResponse
	(*GetConfigResponse)(nil),            // 29: dropz.GetConfigResponse
	(*UpdateConfigResponse)(nil),         // 30: dropz.UpdateConfigResponse
	(*GetSettingResponse)(nil),           // 31: dropz.GetSettingResponse
	(*Config)(nil),                       // 32: dropz.Config
	(*GetLogsResponse)(nil),              // 33: dropz.GetLogsResponse
}
var file_service_proto_depIdxs = []int32{
	0,  // 0: dropz.DropzService.GetDiscoveredCameras:input_type -> dropz.GetDiscoveredCamerasRequest
	0,  // 1: dropz.DropzService.WatchDiscoveredCameras:input_type -> dropz.GetDiscoveredCamerasRequest
	1,  // 2: dropz.DropzService.GetManagedCameras:input_type -> dropz.GetManagedCamerasRequest
	1,  // 3: dropz.DropzService.WatchManagedCameras:input_type -> dropz.GetManagedCamerasRequest
	2,  // 4: dropz.DropzService.ManageCamera:input_type -> dropz.ManageCameraRequest
	3,  // 5: dropz.DropzService.UnmanageCamera:input_type -> dropz.UnmanageCameraRequest
	4,  // 6: dropz.DropzService.PairCamera:input_type -> dropz.PairCameraRequest
	5,  // 7: dropz.DropzService.GetSyncQueue:input_type -> dropz.GetSyncQueueRequest
	5,  // 8: dropz.DropzService.WatchSyncQueue:input_type -> dropz.GetSyncQueueRequest
	6,  // 9: dropz.DropzService.ForceSync:input_type -> dropz.ForceSyncRequest
	7,  // 10: dropz.DropzService.GetGroups:input_type -> dropz.GetGroupsRequest
	8,  // 11: dropz.DropzService.CreateGroup:input_type -> dropz.CreateGroupRequest
	9,  // 12: dropz.DropzService.UpdateGroup:input_type -> dropz.UpdateGroupRequest
	10, // 13: dropz.DropzService.DeleteGroup:input_type -> dropz.DeleteGroupRequest
	11, // 14: dropz.DropzService.GetVideos:input_type -> dropz.GetVideosRequest
	12, // 15: dropz.DropzService.GetConfig:input_type -> dropz.GetConfigRequest
	13, // 16: dropz.DropzService.UpdateConfig:input_type -> dropz.UpdateConfigRequest
	14, // 17: dropz.DropzService.GetSetting:input_type -> dropz.GetSettingRequest
	15, // 18: dropz.DropzService.UpdateSetting:input_type -> dropz.UpdateSettingRequest
	16, // 19: dropz.DropzService.ResetSetting:input_type -> dropz.ResetSettingRequest
	17, // 20: dropz.DropzService.GetLogs:input_type -> dropz.GetLogsRequest
	18, // 21: dropz.DropzService.GetDiscoveredCameras:output_type -> dropz.GetDiscoveredCamerasResponse
	18, // 22: dropz.DropzService.WatchDiscoveredCameras:output_type -> dropz.GetDiscoveredCamerasResponse
	19, // 23: dropz.DropzService.GetManagedCameras:output_type -> dropz.GetManagedCamerasResponse
	19, // 24: dropz.DropzService.WatchManagedCameras:output_type -> dropz.GetManagedCamerasResponse
	20, // 25: dropz.DropzService.ManageCamera:output_type -> dropz.ManageCameraResponse
	21, // 26: dropz.DropzService.UnmanageCamera:output_type -> dropz.UnmanageCameraResponse
	22, // 27: dropz.DropzService.PairCamera:output_type -> dropz.PairCameraResponse
	23, // 28: dropz.DropzService.GetSyncQueue:output_type -> dropz.GetSyncQueueResponse
	23, // 29: dropz.DropzService.WatchSyncQueue:output_type -> dropz.GetSyncQueueResponse
	24, // 30: dropz.DropzService.ForceSync:output_type -> dropz.ForceSyncResponse
	25, // 31: dropz.DropzService.GetGroups:output_type -> dropz.GetGroupsResponse
	26, // 32: dropz.DropzService.CreateGroup:output_type -> dropz.Group
	26, // 33: dropz.DropzService.UpdateGroup:output_type -> dropz.Group
	27, // 34: dropz.DropzService.DeleteGroup:output_type -> dropz.OperationResponse
	28, // 35: dropz.DropzService.GetVideos:output_type -> dropz.GetVideosResponse
	29, // 36: dropz.DropzService.GetConfig:output_type -> dropz.GetConfigResponse
	30, // 37: dropz.DropzService.UpdateConfig:output_type -> dropz.UpdateConfigResponse
	31, // 38: dropz.DropzService.GetSetting:output_type -> dropz.GetSettingResponse
	32, // 39: dropz.DropzService.UpdateSetting:output_type -> dropz.Config
	32, // 40: dropz.DropzService.ResetSetting:output_type -> dropz.Config
	33, // 41: dropz.DropzService.GetLogs:output_type -> dropz.GetLogsResponse
	21, // [21:42] is the sub-list for method output_type
	0,  // [0:21] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	file_gopro_proto_init()
	file_video_proto_init()
	file_logs_proto_init()
	file_config_proto_init()
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
