#!/usr/bin/env python3
"""Generate internal/ble/settings_table.go from the OpenGoPro references.json.

Source: gh-pages branch of gopro/OpenGoPro, references.json at the site root.
Usage: python3 scripts/gen_settings_table.py /path/to/references.json > internal/ble/settings_table.go

Settings with IDs above 255 need the 2-byte ID protocol (Mission 1 family)
and are skipped; dropz speaks the 1-byte protocol.
"""

import json
import sys


def go_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def main() -> None:
    refs = json.load(open(sys.argv[1]))
    settings = refs["settings"]

    print("// Code generated by scripts/gen_settings_table.py from the OpenGoPro")
    print("// references.json (gh-pages). DO NOT EDIT by hand; regenerate instead.")
    print("//")
    print("// Names and option labels only. Which settings and options a given")
    print("// camera supports comes from the camera itself at runtime via")
    print("// GetSettingCapabilities (query 0x32); this table never gates anything.")
    print("package ble")
    print()
    print("// SettingDef describes one OpenGoPro camera setting.")
    print("type SettingDef struct {")
    print("\tName    string")
    print("\tFormat  string // int8ub or int64ub, big-endian")
    print("\tOptions map[int64]string")
    print("}")
    print()
    print("// SettingDefs maps setting ID to its label data.")
    print("var SettingDefs = map[byte]SettingDef{")
    for key in sorted(settings, key=int):
        sid = int(key)
        if sid > 255:
            continue
        s = settings[key]
        fmt_ = s.get("format", "int8ub")
        print(f'\t{sid}: {{Name: "{go_escape(s["name"])}", Format: "{fmt_}", Options: map[int64]string{{')
        for opt_key in sorted(s.get("options", {}), key=int):
            opt = s["options"][opt_key]
            print(f'\t\t{int(opt_key)}: "{go_escape(opt["name"])}",')
        print("\t}},")
    print("}")


if __name__ == "__main__":
    main()
