// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: config.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Configuration settings aligned with OpenAPI spec
type Config struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Core system settings
	PairModeEnabled       bool  `protobuf:"varint,1,opt,name=pair_mode_enabled,json=pairModeEnabled,proto3" json:"pair_mode_enabled,omitempty"` // When true, newly discovered cameras will be automatically paired
	SyncEnabled           bool  `protobuf:"varint,2,opt,name=sync_enabled,json=syncEnabled,proto3" json:"sync_enabled,omitempty"`               // When true, system automatically syncs content from cameras
	ScanIntervalSeconds   int32 `protobuf:"varint,3,opt,name=scan_interval_seconds,json=scanIntervalSeconds,proto3" json:"scan_interval_seconds,omitempty"`
	ConnectTimeoutSeconds int32 `protobuf:"varint,4,opt,name=connect_timeout_seconds,json=connectTimeoutSeconds,proto3" json:"connect_timeout_seconds,omitempty"`
	// Sync behavior settings
	DaysThreshold              int32  `protobuf:"varint,5,opt,name=days_threshold,json=daysThreshold,proto3" json:"days_threshold,omitempty"` // Only sync content newer than this many days
	DestinationFolder          string `protobuf:"bytes,6,opt,name=destination_folder,json=destinationFolder,proto3" json:"destination_folder,omitempty"`
	InactivityTimeoutSeconds   int32  `protobuf:"varint,7,opt,name=inactivity_timeout_seconds,json=inactivityTimeoutSeconds,proto3" json:"inactivity_timeout_seconds,omitempty"`
	StatusCheckIntervalSeconds int32  `protobuf:"varint,12,opt,name=status_check_interval_seconds,json=statusCheckIntervalSeconds,proto3" json:"status_check_interval_seconds,omitempty"` // Interval between BLE status checks (0 = off)
	CheckOnReturn              bool   `protobuf:"varint,13,opt,name=check_on_return,json=checkOnReturn,proto3" json:"check_on_return,omitempty"`                                          // Check for new media when camera reappears
	TurboEnabled               bool   `protobuf:"varint,14,opt,name=turbo_enabled,json=turboEnabled,proto3" json:"turbo_enabled,omitempty"`                                               // Use Turbo Transfer during media offload
	// Camera behavior settings
	SetTimeEnabled bool `protobuf:"varint,9,opt,name=set_time_enabled,json=setTimeEnabled,proto3" json:"set_time_enabled,omitempty"` // Set camera time when connecting
	// Additional settings
	LogLevel      string                 `protobuf:"bytes,10,opt,name=log_level,json=logLevel,proto3" json:"log_level,omitempty"`
	LastUpdated   *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetPairModeEnabled() bool {
	if x != nil {
		return x.PairModeEnabled
	}
	return false
}

func (x *Config) GetSyncEnabled() bool {
	if x != nil {
		return x.SyncEnabled
	}
	return false
}

func (x *Config) GetScanIntervalSeconds() int32 {
	if x != nil {
		return x.ScanIntervalSeconds
	}
	return 0
}

func (x *Config) GetConnectTimeoutSeconds() int32 {
	if x != nil {
		return x.ConnectTimeoutSeconds
	}
	return 0
}

func (x *Config) GetDaysThreshold() int32 {
	if x != nil {
		return x.DaysThreshold
	}
	return 0
}

func (x *Config) GetDestinationFolder() string {
	if x != nil {
		return x.DestinationFolder
	}
	return ""
}

func (x *Config) GetInactivityTimeoutSeconds() int32 {
	if x != nil {
		return x.InactivityTimeoutSeconds
	}
	return 0
}

func (x *Config) GetStatusCheckIntervalSeconds() int32 {
	if x != nil {
		return x.StatusCheckIntervalSeconds
	}
	return 0
}

func (x *Config) GetCheckOnReturn() bool {
	if x != nil {
		return x.CheckOnReturn
	}
	return false
}

func (x *Config) GetTurboEnabled() bool {
	if x != nil {
		return x.TurboEnabled
	}
	return false
}

func (x *Config) GetSetTimeEnabled() bool {
	if x != nil {
		return x.SetTimeEnabled
	}
	return false
}

func (x *Config) GetLogLevel() string {
	if x != nil {
		return x.LogLevel
	}
	return ""
}

func (x *Config) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

// Request to get configuration
type GetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigRequest) Reset() {
	*x = GetConfigRequest{}
	mi := &file_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigRequest) ProtoMessage() {}

func (x *GetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigRequest.ProtoReflect.Descriptor instead.
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{1}
}

// Response with configuration
type GetConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *Config                `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigResponse) Reset() {
	*x = GetConfigResponse{}
	mi := &file_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigResponse) ProtoMessage() {}

func (x *GetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigResponse.ProtoReflect.Descriptor instead.
func (*GetConfigResponse) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{2}
}

func (x *GetConfigResponse) GetConfig() *Config {
	if x != nil {
		return x.Config
	}
	return nil
}

// Request to update configuration
type UpdateConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *Config                `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConfigRequest) Reset() {
	*x = UpdateConfigRequest{}
	mi := &file_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigRequest) ProtoMessage() {}

func (x *UpdateConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateConfigRequest) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateConfigRequest) GetConfig() *Config {
	if x != nil {
		return x.Config
	}
	return nil
}

// Response for update configuration request
type UpdateConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Config        *Config                `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConfigResponse) Reset() {
	*x = UpdateConfigResponse{}
	mi := &file_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigResponse) ProtoMessage() {}

func (x *UpdateConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfigResponse.ProtoReflect.Descriptor instead.
func (*UpdateConfigResponse) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateConfigResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateConfigResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateConfigResponse) GetConfig() *Config {
	if x != nil {
		return x.Config
	}
	return nil
}

// Request to get a specific setting
type GetSettingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SettingName   string                 `protobuf:"bytes,1,opt,name=setting_name,json=settingName,proto3" json:"setting_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSettingRequest) Reset() {
	*x = GetSettingRequest{}
	mi := &file_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSettingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSettingRequest) ProtoMessage() {}

func (x *GetSettingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSettingRequest.ProtoReflect.Descriptor instead.
func (*GetSettingRequest) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{5}
}

func (x *GetSettingRequest) GetSettingName() string {
	if x != nil {
		return x.SettingName
	}
	return ""
}

// Response with a specific setting value
type GetSettingResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*GetSettingResponse_BoolValue
	//	*GetSettingResponse_IntValue
	//	*GetSettingResponse_StringValue
	Value         isGetSettingResponse_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSettingResponse) Reset() {
	*x = GetSettingResponse{}
	mi := &file_config_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSettingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSettingResponse) ProtoMessage() {}

func (x *GetSettingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSettingResponse.ProtoReflect.Descriptor instead.
func (*GetSettingResponse) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{6}
}

func (x *GetSettingResponse) GetValue() isGetSettingResponse_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GetSettingResponse) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*GetSettingResponse_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *GetSettingResponse) GetIntValue() int32 {
	if x != nil {
		if x, ok := x.Value.(*GetSettingResponse_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *GetSettingResponse) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*GetSettingResponse_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

type isGetSettingResponse_Value interface {
	isGetSettingResponse_Value()
}

type GetSettingResponse_BoolValue struct {
	BoolValue bool `protobuf:"varint,1,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type GetSettingResponse_IntValue struct {
	IntValue int32 `protobuf:"varint,2,opt,name=int_value,json=intValue,proto3,oneof"`
}

type GetSettingResponse_StringValue struct {
	StringValue string `protobuf:"bytes,3,opt,name=string_value,json=stringValue,proto3,oneof"`
}

func (*GetSettingResponse_BoolValue) isGetSettingResponse_Value() {}

func (*GetSettingResponse_IntValue) isGetSettingResponse_Value() {}

func (*GetSettingResponse_StringValue) isGetSettingResponse_Value() {}

// Request to update a specific setting
type UpdateSettingRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	SettingName string                 `protobuf:"bytes,1,opt,name=setting_name,json=settingName,proto3" json:"setting_name,omitempty"`
	// Types that are valid to be assigned to Value:
	//
	//	*UpdateSettingRequest_BoolValue
	//	*UpdateSettingRequest_IntValue
	//	*UpdateSettingRequest_StringValue
	Value         isUpdateSettingRequest_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSettingRequest) Reset() {
	*x = UpdateSettingRequest{}
	mi := &file_config_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSettingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSettingRequest) ProtoMessage() {}

func (x *UpdateSettingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSettingRequest.ProtoReflect.Descriptor instead.
func (*UpdateSettingRequest) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateSettingRequest) GetSettingName() string {
	if x != nil {
		return x.SettingName
	}
	return ""
}

func (x *UpdateSettingRequest) GetValue() isUpdateSettingRequest_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *UpdateSettingRequest) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*UpdateSettingRequest_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *UpdateSettingRequest) GetIntValue() int32 {
	if x != nil {
		if x, ok := x.Value.(*UpdateSettingRequest_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *UpdateSettingRequest) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*UpdateSettingRequest_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

type isUpdateSettingRequest_Value interface {
	isUpdateSettingRequest_Value()
}

type UpdateSettingRequest_BoolValue struct {
	BoolValue bool `protobuf:"varint,2,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type UpdateSettingRequest_IntValue struct {
	IntValue int32 `protobuf:"varint,3,opt,name=int_value,json=intValue,proto3,oneof"`
}

type UpdateSettingRequest_StringValue struct {
	StringValue string `protobuf:"bytes,4,opt,name=string_value,json=stringValue,proto3,oneof"`
}

func (*UpdateSettingRequest_BoolValue) isUpdateSettingRequest_Value() {}

func (*UpdateSettingRequest_IntValue) isUpdateSettingRequest_Value() {}

func (*UpdateSettingRequest_StringValue) isUpdateSettingRequest_Value() {}

// Request to reset a specific setting to default
type ResetSettingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SettingName   string                 `protobuf:"bytes,1,opt,name=setting_name,json=settingName,proto3" json:"setting_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetSettingRequest) Reset() {
	*x = ResetSettingRequest{}
	mi := &file_config_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetSettingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetSettingRequest) ProtoMessage() {}

func (x *ResetSettingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetSettingRequest.ProtoReflect.Descriptor instead.
func (*ResetSettingRequest) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{8}
}

func (x *ResetSettingRequest) GetSettingName() string {
	if x != nil {
		return x.SettingName
	}
	return ""
}

var File_config_proto protoreflect.FileDescriptor

const file_config_proto_rawDesc = "" +
	"\n" +
	"\fconfig.proto\x12\x05dropz\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf3\x04\n" +
	"\x06Config\x12*\n" +
	"\x11pair_mode_enabled\x18\x01 \x01(\bR\x0fpairModeEnabled\x12!\n" +
	"\fsync_enabled\x18\x02 \x01(\bR\vsyncEnabled\x122\n" +
	"\x15scan_interval_seconds\x18\x03 \x01(\x05R\x13scanIntervalSeconds\x126\n" +
	"\x17connect_timeout_seconds\x18\x04 \x01(\x05R\x15connectTimeoutSeconds\x12%\n" +
	"\x0edays_threshold\x18\x05 \x01(\x05R\rdaysThreshold\x12-\n" +
	"\x12destination_folder\x18\x06 \x01(\tR\x11destinationFolder\x12<\n" +
	"\x1ainactivity_timeout_seconds\x18\a \x01(\x05R\x18inactivityTimeoutSeconds\x12A\n" +
	"\x1dstatus_check_interval_seconds\x18\f \x01(\x05R\x1astatusCheckIntervalSeconds\x12&\n" +
	"\x0fcheck_on_return\x18\r \x01(\bR\rcheckOnReturn\x12#\n" +
	"\rturbo_enabled\x18\x0e \x01(\bR\fturboEnabled\x12(\n" +
	"\x10set_time_enabled\x18\t \x01(\bR\x0esetTimeEnabled\x12\x1b\n" +
	"\tlog_level\x18\n" +
	" \x01(\tR\blogLevel\x12=\n" +
	"\flast_updated\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\vlastUpdatedJ\x04\b\b\x10\t\"\x12\n" +
	"\x10GetConfigRequest\":\n" +
	"\x11GetConfigResponse\x12%\n" +
	"\x06config\x18\x01 \x01(\v2\r.dropz.ConfigR\x06config\"<\n" +
	"\x13UpdateConfigRequest\x12%\n" +
	"\x06config\x18\x01 \x01(\v2\r.dropz.ConfigR\x06config\"q\n" +
	"\x14UpdateConfigResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12%\n" +
	"\x06config\x18\x03 \x01(\v2\r.dropz.ConfigR\x06config\"6\n" +
	"\x11GetSettingRequest\x12!\n" +
	"\fsetting_name\x18\x01 \x01(\tR\vsettingName\"\x82\x01\n" +
	"\x12GetSettingResponse\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x01 \x01(\bH\x00R\tboolValue\x12\x1d\n" +
	"\tint_value\x18\x02 \x01(\x05H\x00R\bintValue\x12#\n" +
	"\fstring_value\x18\x03 \x01(\tH\x00R\vstringValueB\a\n" +
	"\x05value\"\xa7\x01\n" +
	"\x14UpdateSettingRequest\x12!\n" +
	"\fsetting_name\x18\x01 \x01(\tR\vsettingName\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x02 \x01(\bH\x00R\tboolValue\x12\x1d\n" +
	"\tint_value\x18\x03 \x01(\x05H\x00R\bintValue\x12#\n" +
	"\fstring_value\x18\x04 \x01(\tH\x00R\vstringValueB\a\n" +
	"\x05value\"8\n" +
	"\x13ResetSettingRequest\x12!\n" +
	"\fsetting_name\x18\x01 \x01(\tR\vsettingNameB*Z(github.com/dropz/dropz/internal/protocolb\x06proto3"

var (
	file_config_proto_rawDescOnce sync.Once
	file_config_proto_rawDescData []byte
)

func file_config_proto_rawDescGZIP() []byte {
	file_config_proto_rawDescOnce.Do(func() {
		file_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_config_proto_rawDesc), len(file_config_proto_rawDesc)))
	})
	return file_config_proto_rawDescData
}

var file_config_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_config_proto_goTypes = []any{
	(*Config)(nil),                // 0: dropz.Config
	(*GetConfigRequest)(nil),      // 1: dropz.GetConfigRequest
	(*GetConfigResponse)(nil),     // 2: dropz.GetConfigResponse
	(*UpdateConfigRequest)(nil),   // 3: dropz.UpdateConfigRequest
	(*UpdateConfigResponse)(nil),  // 4: dropz.UpdateConfigResponse
	(*GetSettingRequest)(nil),     // 5: dropz.GetSettingRequest
	(*GetSettingResponse)(nil),    // 6: dropz.GetSettingResponse
	(*UpdateSettingRequest)(nil),  // 7: dropz.UpdateSettingRequest
	(*ResetSettingRequest)(nil),   // 8: dropz.ResetSettingRequest
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_config_proto_depIdxs = []int32{
	9, // 0: dropz.Config.last_updated:type_name -> google.protobuf.Timestamp
	0, // 1: dropz.GetConfigResponse.config:type_name -> dropz.Config
	0, // 2: dropz.UpdateConfigRequest.config:type_name -> dropz.Config
	0, // 3: dropz.UpdateConfigResponse.config:type_name -> dropz.Config
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_config_proto_init() }
func file_config_proto_init() {
	if File_config_proto != nil {
		return
	}
	file_config_proto_msgTypes[6].OneofWrappers = []any{
		(*GetSettingResponse_BoolValue)(nil),
		(*GetSettingResponse_IntValue)(nil),
		(*GetSettingResponse_StringValue)(nil),
	}
	file_config_proto_msgTypes[7].OneofWrappers = []any{
		(*UpdateSettingRequest_BoolValue)(nil),
		(*UpdateSettingRequest_IntValue)(nil),
		(*UpdateSettingRequest_StringValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_proto_rawDesc), len(file_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_config_proto_goTypes,
		DependencyIndexes: file_config_proto_depIdxs,
		MessageInfos:      file_config_proto_msgTypes,
	}.Build()
	File_config_proto = out.File
	file_config_proto_goTypes = nil
	file_config_proto_depIdxs = nil
}
