// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: gopro.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Base Camera type with common properties
type Camera struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Alias         string                 `protobuf:"bytes,3,opt,name=alias,proto3" json:"alias,omitempty"`
	BleAddress    string                 `protobuf:"bytes,4,opt,name=ble_address,json=bleAddress,proto3" json:"ble_address,omitempty"`
	WifiSsid      string                 `protobuf:"bytes,5,opt,name=wifi_ssid,json=wifiSsid,proto3" json:"wifi_ssid,omitempty"`
	WifiPassword  string                 `protobuf:"bytes,6,opt,name=wifi_password,json=wifiPassword,proto3" json:"wifi_password,omitempty"`
	Rssi          int32                  `protobuf:"varint,7,opt,name=rssi,proto3" json:"rssi,omitempty"` // Signal strength in dBm
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Camera) Reset() {
	*x = Camera{}
	mi := &file_gopro_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Camera) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Camera) ProtoMessage() {}

func (x *Camera) ProtoReflect() protoreflect.Message {
	mi := &file_gopro_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Camera.ProtoReflect.Descriptor instead.
func (*Camera) Descriptor() ([]byte, []int) {
	return file_gopro_proto_rawDescGZIP(), []int{0}
}

func (x *Camera) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Camera) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Camera) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *Camera) GetBleAddress() string {
	if x != nil {
		return x.BleAddress
	}
	return ""
}

func (x *Camera) GetWifiSsid() string {
	if x != nil {
		return x.WifiSsid
	}
	return ""
}

func (x *Camera) GetWifiPassword() string {
	if x != nil {
		return x.WifiPassword
	}
	return ""
}

func (x *Camera) GetRssi() int32 {
	if x != nil {
		return x.Rssi
	}
	return 0
}

// Camera status information
type CameraStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LastSeen      *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	LastSynced    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=last_synced,json=lastSynced,proto3" json:"last_synced,omitempty"`
	IsPairing     bool                   `protobuf:"varint,3,opt,name=is_pairing,json=isPairing,proto3" json:"is_pairing,omitempty"`
	IsPaired      bool                   `protobuf:"varint,4,opt,name=is_paired,json=isPaired,proto3" json:"is_paired,omitempty"`
	IsManaged     bool                   `protobuf:"varint,5,opt,name=is_managed,json=isManaged,proto3" json:"is_managed,omitempty"`
	IsReachable   bool                   `protobuf:"varint,6,opt,name=is_reachable,json=isReachable,proto3" json:"is_reachable,omitempty"`
	IsSynced      bool                   `protobuf:"varint,7,opt,name=is_synced,json=isSynced,proto3" json:"is_synced,omitempty"`
	IsSyncing     bool                   `protobuf:"varint,8,opt,name=is_syncing,json=isSyncing,proto3" json:"is_syncing,omitempty"`
	LastSyncError string                 `protobuf:"bytes,9,opt,name=last_sync_error,json=lastSyncError,proto3" json:"last_sync_error,omitempty"`
	// Camera-side pairing UI flag, read from BLE advertising data
	InPairingMode bool `protobuf:"varint,10,opt,name=in_pairing_mode,json=inPairingMode,proto3" json:"in_pairing_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CameraStatus) Reset() {
	*x = CameraStatus{}
	mi := &file_gopro_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CameraStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CameraStatus) ProtoMessage() {}

func (x *CameraStatus) ProtoReflect() protoreflect.Message {
	mi := &file_gopro_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CameraStatus.ProtoReflect.Descriptor instead.
func (*CameraStatus) Descriptor() ([]byte, []int) {
	return file_gopro_proto_rawDescGZIP(), []int{1}
}

func (x *CameraStatus) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

func (x *CameraStatus) GetLastSynced() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSynced
	}
	return nil
}

func (x *CameraStatus) GetIsPairing() bool {
	if x != nil {
		return x.IsPairing
	}
	return false
}

func (x *CameraStatus) GetIsPaired() bool {
	if x != nil {
		return x.IsPaired
	}
	return false
}

func (x *CameraStatus) GetIsManaged() bool {
	if x != nil {
		return x.IsManaged
	}
	return false
}

func (x *CameraStatus) GetIsReachable() bool {
	if x != nil {
		return x.IsReachable
	}
	return false
}

func (x *CameraStatus) GetIsSynced() bool {
	if x != nil {
		return x.IsSynced
	}
	return false
}

func (x *CameraStatus) GetIsSyncing() bool {
	if x != nil {
		return x.IsSyncing
	}
	return false
}

func (x *CameraStatus) GetLastSyncError() string {
	if x != nil {
		return x.LastSyncError
	}
	return ""
}

func (x *CameraStatus) GetInPairingMode() bool {
	if x != nil {
		return x.InPairingMode
	}
	return false
}

// Additional technical metadata about a camera
type CameraMetadata struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // References the camera ID
	FirmwareVersion  string                 `protobuf:"bytes,2,opt,name=firmware_version,json=firmwareVersion,proto3" json:"firmware_version,omitempty"`
	Model            string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	SerialNumber     string                 `protobuf:"bytes,4,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	BatteryLevel     int32                  `protobuf:"varint,5,opt,name=battery_level,json=batteryLevel,proto3" json:"battery_level,omitempty"` // percentage
	HardwareVersion  string                 `protobuf:"bytes,7,opt,name=hardware_version,json=hardwareVersion,proto3" json:"hardware_version,omitempty"`
	NumPhotos        int32                  `protobuf:"varint,8,opt,name=num_photos,json=numPhotos,proto3" json:"num_photos,omitempty"`
	NumVideos        int32                  `protobuf:"varint,9,opt,name=num_videos,json=numVideos,proto3" json:"num_videos,omitempty"`
	SdCardStatus     int32                  `protobuf:"varint,10,opt,name=sd_card_status,json=sdCardStatus,proto3" json:"sd_card_status,omitempty"`
	RemainingSpaceKb int64                  `protobuf:"varint,11,opt,name=remaining_space_kb,json=remainingSpaceKb,proto3" json:"remaining_space_kb,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CameraMetadata) Reset() {
	*x = CameraMetadata{}
	mi := &file_gopro_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CameraMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CameraMetadata) ProtoMessage() {}

func (x *CameraMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_gopro_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CameraMetadata.ProtoReflect.Descriptor instead.
func (*CameraMetadata) Descriptor() ([]byte, []int) {
	return file_gopro_proto_rawDescGZIP(), []int{2}
}

func (x *CameraMetadata) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CameraMetadata) GetFirmwareVersion() string {
	if x != nil {
		return x.FirmwareVersion
	}
	return ""
}

func (x *CameraMetadata) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CameraMetadata) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *CameraMetadata) GetBatteryLevel() int32 {
	if x != nil {
		return x.BatteryLevel
	}
	return 0
}

func (x *CameraMetadata) GetHardwareVersion() string {
	if x != nil {
		return x.HardwareVersion
	}
	return ""
}

func (x *CameraMetadata) GetNumPhotos() int32 {
	if x != nil {
		return x.NumPhotos
	}
	return 0
}

func (x *CameraMetadata) GetNumVideos() int32 {
	if x != nil {
		return x.NumVideos
	}
	return 0
}

func (x *CameraMetadata) GetSdCardStatus() int32 {
	if x != nil {
		return x.SdCardStatus
	}
	return 0
}

func (x *CameraMetadata) GetRemainingSpaceKb() int64 {
	if x != nil {
		return x.RemainingSpaceKb
	}
	return 0
}

// Complete camera with all its information
type CameraWithState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Camera        *Camera                `protobuf:"bytes,1,opt,name=camera,proto3" json:"camera,omitempty"`
	Status        *CameraStatus          `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	GroupId       string                 `protobuf:"bytes,3,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Metadata      *CameraMetadata        `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CameraWithState) Reset() {
	*x = CameraWithState{}
	mi := &file_gopro_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CameraWithState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CameraWithState) ProtoMessage() {}

func (x *CameraWithState) ProtoReflect() protoreflect.Message {
	mi := &file_gopro_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CameraWithState.ProtoReflect.Descriptor instead.
func (*CameraWithState) Descriptor() ([]byte, []int) {
	return file_gopro_proto_rawDescGZIP(), []int{3}
}

func (x *CameraWithState) GetCamera() *Camera {
	if x != nil {
		return x.Camera
	}
	return nil
}

func (x *CameraWithState) GetStatus() *CameraStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *CameraWithState) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *CameraWithState) GetMetadata() *CameraMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Discovered cameras - cameras that are not managed or paired
type DiscoveredCamera struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CameraState   *CameraWithState       `protobuf:"bytes,1,opt,name=camera_state,json=cameraState,proto3" json:"camera_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoveredCamera) Reset() {
	*x = DiscoveredCamera{}
	mi := &file_gopro_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoveredCamera) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveredCamera) ProtoMessage() {}

func (x *DiscoveredCamera) ProtoReflect() protoreflect.Message {
	mi := &file_gopro_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoveredCamera.ProtoReflect.Descriptor instead.
func (*DiscoveredCamera) Descriptor() ([]byte, []int) {
	return file_gopro_proto_rawDescGZIP(), []int{4}
}

func (x *DiscoveredCamera) GetCameraState() *CameraWithState {
	if x != nil {
		return x.CameraState
	}
	return nil
}

// Managed Camera (Camera Pool) - managed and paired cameras
type ManagedCamera struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CameraState   *CameraWithState       `protobuf:"bytes,1,opt,name=camera_state,json=cameraState,proto3" json:"camera_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManagedCamera) Reset() {
	*x = ManagedCamera{}
	mi := &file_gopro_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagedCamera) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagedCamera) ProtoMessage() {}

func (x *ManagedCamera) ProtoReflect() protoreflect.Message {
	mi := &file_gopro_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagedCamera.ProtoReflect.Descriptor instead.
func (*ManagedCamera) Descriptor() ([]byte, []int) {
	return file_gopro_proto_rawDescGZIP(), []int{5}
}

func (x *ManagedCamera) GetCameraState() *CameraWithState {
	if x != nil {
		return x.CameraState
	}
	return nil
}

// Sync Queue Entry
type SyncQueueEntry struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CameraId         string                 `protobuf:"bytes,1,opt,name=camera_id,json=cameraId,proto3" json:"camera_id,omitempty"` // References the camera ID
	QueuedAt         *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=queued_at,json=queuedAt,proto3" json:"queued_at,omitempty"`
	Priority         int32                  `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"` // Higher numbers = higher priority (manual sync = 10, auto sync = 5)
	ProgressPercent  int32                  `protobuf:"varint,4,opt,name=progress_percent,json=progressPercent,proto3" json:"progress_percent,omitempty"`
	CurrentOperation string                 `protobuf:"bytes,5,opt,name=current_operation,json=currentOperation,proto3" json:"current_operation,omitempty"` // Text description of current operation
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SyncQueueEntry) Reset() {
	*x = SyncQueueEntry{}
	mi := &file_gopro_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncQueueEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncQueueEntry) ProtoMessage() {}

func (x *SyncQueueEntry) ProtoReflect() protoreflect.Message {
	mi := &file_gopro_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncQueueEntry.ProtoReflect.Descriptor instead.
func (*SyncQueueEntry) Descriptor() ([]byte, []int) {
	return file_gopro_proto_rawDescGZIP(), []int{6}
}

func (x *SyncQueueEntry) GetCameraId() string {
	if x != nil {
		return x.CameraId
	}
	return ""
}

func (x *SyncQueueEntry) GetQueuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.QueuedAt
	}
	return nil
}

func (x *SyncQueueEntry) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *SyncQueueEntry) GetProgressPercent() int32 {
	if x != nil {
		return x.ProgressPercent
	}
	return 0
}

func (x *SyncQueueEntry) GetCurrentOperation() string {
	if x != nil {
		return x.CurrentOperation
	}
	return ""
}

// Group of cameras
type Group struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CameraIds     []string               `protobuf:"bytes,3,rep,name=camera_ids,json=cameraIds,proto3" json:"camera_ids,omitempty"` // References to managed cameras
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Group) Reset() {
	*x = Group{}
	mi := &file_gopro_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Group) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Group) ProtoMessage() {}

func (x *Group) ProtoReflect() protoreflect.Message {
	mi := &file_gopro_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Group.ProtoReflect.Descriptor instead.
func (*Group) Descriptor() ([]byte, []int) {
	return file_gopro_proto_rawDescGZIP(), []int{7}
}

func (x *Group) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Group) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Group) GetCameraIds() []string {
	if x != nil {
		return x.CameraIds
	}
	return nil
}

func (x *Group) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Group) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Request to get all discovered cameras
type GetDiscoveredCamerasRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChangeCounter int64                  `protobuf:"varint,1,opt,name=change_counter,json=changeCounter,proto3" json:"change_counter,omitempty"` // Client's current change counter, used for change tracking
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDiscoveredCamerasRequest) Reset() {
	*x = GetDiscoveredCamerasRequest{}
	mi := &file_gopro_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDiscoveredCamerasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiscoveredCamerasRequest) ProtoMessage() {}

func (x *GetDiscoveredCamerasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gopro_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiscoveredCamerasRequest.ProtoReflect.Descriptor instead.
func (*GetDiscoveredCamerasRequest) Descriptor() ([]byte, []int) {
	return file_gopro_proto_rawDescGZIP(), []int{8}
}

func (x *GetDiscoveredCamerasRequest) GetChangeCounter() int64 {
	if x != nil {
		return x.ChangeCounter
	}
	return 0
}

// Response with all discovered cameras
type GetDiscoveredCamerasResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cameras       []*DiscoveredCamera    `protobuf:"bytes,1,rep,name=cameras,proto3" json:"cameras,omitempty"`
	ChangeCounter int64                  `protobuf:"varint,2,opt,name=change_counter,json=changeCounter,proto3" json:"change_counter,omitempty"` // Server's current change counter
	NoChanges     bool                   `protobuf:"varint,3,opt,name=no_changes,json=noChanges,proto3" json:"no_changes,omitempty"`             // True if no changes since the client's counter
	Heartbeat     bool                   `protobuf:"varint,4,opt,name=heartbeat,proto3" json:"heartbeat,omitempty"`                              // True if this is just a keepalive ping
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDiscoveredCamerasResponse) Reset() {
	*x = GetDiscoveredCamerasResponse{}
	mi := &file_gopro_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDiscoveredCamerasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiscoveredCamerasResponse) ProtoMessage() {}

func (x *GetDiscoveredCamerasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gopro_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiscoveredCamerasResponse.ProtoReflect.Descriptor instead.
func (*GetDiscoveredCamerasResponse) Descriptor() ([]byte, []int) {
	return file_gopro_proto_rawDescGZIP(), []int{9}
}

func (x *GetDiscoveredCamerasResponse) GetCameras() []*DiscoveredCamera {
	if x != nil {
		return x.Cameras
	}
	return nil
}

func (x *GetDiscoveredCamerasResponse) GetChangeCounter() int64 {
	if x != nil {
		return x.ChangeCounter
	}
	return 0
}

func (x *GetDiscoveredCamerasResponse) GetNoChanges() bool {
	if x != nil {
		return x.NoChanges
	}
	return false
}

func (x *GetDiscoveredCamerasResponse) GetHeartbeat() bool {
	if x != nil {
		return x.Heartbeat
	}
	return false
}

// Request to get cameras in the pool (managed and paired)
type GetManagedCamerasRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChangeCounter int64                  `protobuf:"varint,1,opt,name=change_counter,json=changeCounter,proto3" json:"change_counter,omitempty"` // Client's current change counter, used for change tracking
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetManagedCamerasRequest) Reset() {
	*x = GetManagedCamerasRequest{}
	mi := &file_gopro_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetManagedCamerasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetManagedCamerasRequest) ProtoMessage() {}

func (x *GetManagedCamerasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gopro_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetManagedCamerasRequest.ProtoReflect.Descriptor instead.
func (*GetManagedCamerasRequest) Descriptor() ([]byte, []int) {
	return file_gopro_proto_rawDescGZIP(), []int{10}
}

func (x *GetManagedCamerasRequest) GetChangeCounter() int64 {
	if x != nil {
		return x.ChangeCounter
	}
	return 0
}

// Response with all managed cameras
type GetManagedCamerasResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cameras       []*ManagedCamera       `protobuf:"bytes,1,rep,name=cameras,proto3" json:"cameras,omitempty"`
	ChangeCounter int64                  `protobuf:"varint,2,opt,name=change_counter,json=changeCounter,proto3" json:"change_counter,omitempty"` // Server's current change counter
	NoChanges     bool                   `protobuf:"varint,3,opt,name=no_changes,json=noChanges,proto3" json:"no_changes,omitempty"`             // True if no changes since the client's counter
	Heartbeat     bool                   `protobuf:"varint,4,opt,name=heartbeat,proto3" json:"heartbeat,omitempty"`                              // True if this is just a keepalive ping
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetManagedCamerasResponse) Reset() {
	*x = GetManagedCamerasResponse{}
	mi := &file_gopro_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetManagedCamerasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetManagedCamerasResponse) ProtoMessage() {}

func (x *GetManagedCamerasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gopro_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetManagedCamerasResponse.ProtoReflect.Descriptor instead.
func (*GetManagedCamerasResponse) Descriptor() ([]byte, []int) {
	return file_gopro_proto_rawDescGZIP(), []int{11}
}

func (x *GetManagedCamerasResponse) GetCameras() []*ManagedCamera {
	if x != nil {
		return x.Cameras
	}
	return nil
}

func (x *GetManagedCamerasResponse) GetChangeCounter() int64 {
	if x != nil {
		return x.ChangeCounter
	}
	return 0
}

func (x *GetManagedCamerasResponse) GetNoChanges() bool {
	if x != nil {
		return x.NoChanges
	}
	return false
}

func (x *GetManagedCamerasResponse) GetHeartbeat() bool {
	if x != nil {
		return x.Heartbeat
	}
	return false
}

// Request to get the sync queue
type GetSyncQueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChangeCounter int64                  `protobuf:"varint,1,opt,name=change_counter,json=changeCounter,proto3" json:"change_counter,omitempty"` // Client's current change counter, used for change tracking
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSyncQueueRequest) Reset() {
	*x = GetSyncQueueRequest{}
	mi := &file_gopro_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSyncQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSyncQueueRequest) ProtoMessage() {}

func (x *GetSyncQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gopro_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSyncQueueRequest.ProtoReflect.Descriptor instead.
func (*GetSyncQueueRequest) Descriptor() ([]byte, []int) {
	return file_gopro_proto_rawDescGZIP(), []int{12}
}

func (x *GetSyncQueueRequest) GetChangeCounter() int64 {
	if x != nil {
		return x.ChangeCounter
	}
	return 0
}

// Response with the sync queue
type GetSyncQueueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queue         []*SyncQueueEntry      `protobuf:"bytes,1,rep,name=queue,proto3" json:"queue,omitempty"`
	ChangeCounter int64                  `protobuf:"varint,2,opt,name=change_counter,json=changeCounter,proto3" json:"change_counter,omitempty"` // Server's current change counter
	NoChanges     bool                   `protobuf:"varint,3,opt,name=no_changes,json=noChanges,proto3" json:"no_changes,omitempty"`             // True if no changes since the client's counter
	Heartbeat     bool                   `protobuf:"varint,4,opt,name=heartbeat,proto3" json:"heartbeat,omitempty"`                              // True if this is just a keepalive ping
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSyncQueueResponse) Reset() {
	*x = GetSyncQueueResponse{}
	mi := &file_gopro_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSyncQueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSyncQueueResponse) ProtoMessage() {}

func (x *GetSyncQueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gopro_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSyncQueueResponse.ProtoReflect.Descriptor instead.
func (*GetSyncQueueResponse) Descriptor() ([]byte, []int) {
	return file_gopro_proto_rawDescGZIP(), []int{13}
}

func (x *GetSyncQueueResponse) GetQueue() []*SyncQueueEntry {
	if x != nil {
		return x.Queue
	}
	return nil
}

func (x *GetSyncQueueResponse) GetChangeCounter() int64 {
	if x != nil {
		return x.ChangeCounter
	}
	return 0
}

func (x *GetSyncQueueResponse) GetNoChanges() bool {
	if x != nil {
		return x.NoChanges
	}
	return false
}

func (x *GetSyncQueueResponse) GetHeartbeat() bool {
	if x != nil {
		return x.Heartbeat
	}
	return false
}

// Request to manage a specific camera (add to camera pool)
type ManageCameraRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CameraId      string                 `protobuf:"bytes,1,opt,name=camera_id,json=cameraId,proto3" json:"camera_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManageCameraRequest) Reset() {
	*x = ManageCameraRequest{}
	mi := &file_gopro_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManageCameraRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManageCameraRequest) ProtoMessage() {}

func (x *ManageCameraRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gopro_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManageCameraRequest.ProtoReflect.Descriptor instead.
func (*ManageCameraRequest) Descriptor() ([]byte, []int) {
	return file_gopro_proto_rawDescGZIP(), []int{14}
}

func (x *ManageCameraRequest) GetCameraId() string {
	if x != nil {
		return x.CameraId
	}
	return ""
}

// Response for manage request
type ManageCameraResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Camera        *ManagedCamera         `protobuf:"bytes,3,opt,name=camera,proto3" json:"camera,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManageCameraResponse) Reset() {
	*x = ManageCameraResponse{}
	mi := &file_gopro_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManageCameraResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManageCameraResponse) ProtoMessage() {}

func (x *ManageCameraResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gopro_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManageCameraResponse.ProtoReflect.Descriptor instead.
func (*ManageCameraResponse) Descriptor() ([]byte, []int) {
	return file_gopro_proto_rawDescGZIP(), []int{15}
}

func (x *ManageCameraResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ManageCameraResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ManageCameraResponse) GetCamera() *ManagedCamera {
	if x != nil {
		return x.Camera
	}
	return nil
}

// Request to stop managing a specific camera
type UnmanageCameraRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CameraId      string                 `protobuf:"bytes,1,opt,name=camera_id,json=cameraId,proto3" json:"camera_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnmanageCameraRequest) Reset() {
	*x = UnmanageCameraRequest{}
	mi := &file_gopro_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnmanageCameraRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnmanageCameraRequest) ProtoMessage() {}

func (x *UnmanageCameraRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gopro_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnmanageCameraRequest.ProtoReflect.Descriptor instead.
func (*UnmanageCameraRequest) Descriptor() ([]byte, []int) {
	return file_gopro_proto_rawDescGZIP(), []int{16}
}

func (x *UnmanageCameraRequest) GetCameraId() string {
	if x != nil {
		return x.CameraId
	}
	return ""
}

// Response for unmanage request
type UnmanageCameraResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnmanageCameraResponse) Reset() {
	*x = UnmanageCameraResponse{}
	mi := &file_gopro_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnmanageCameraResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnmanageCameraResponse) ProtoMessage() {}

func (x *UnmanageCameraResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gopro_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnmanageCameraResponse.ProtoReflect.Descriptor instead.
func (*UnmanageCameraResponse) Descriptor() ([]byte, []int) {
	return file_gopro_proto_rawDescGZIP(), []int{17}
}

func (x *UnmanageCameraResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UnmanageCameraResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Request to pair a specific camera
type PairCameraRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CameraId      string                 `protobuf:"bytes,1,opt,name=camera_id,json=cameraId,proto3" json:"camera_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PairCameraRequest) Reset() {
	*x = PairCameraRequest{}
	mi := &file_gopro_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PairCameraRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairCameraRequest) ProtoMessage() {}

func (x *PairCameraRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gopro_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairCameraRequest.ProtoReflect.Descriptor instead.
func (*PairCameraRequest) Descriptor() ([]byte, []int) {
	return file_gopro_proto_rawDescGZIP(), []int{18}
}

func (x *PairCameraRequest) GetCameraId() string {
	if x != nil {
		return x.CameraId
	}
	return ""
}

// Response for pair request
type PairCameraResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Camera        *ManagedCamera         `protobuf:"bytes,3,opt,name=camera,proto3" json:"camera,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PairCameraResponse) Reset() {
	*x = PairCameraResponse{}
	mi := &file_gopro_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PairCameraResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairCameraResponse) ProtoMessage() {}

func (x *PairCameraResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gopro_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairCameraResponse.ProtoReflect.Descriptor instead.
func (*PairCameraResponse) Descriptor() ([]byte, []int) {
	return file_gopro_proto_rawDescGZIP(), []int{19}
}

func (x *PairCameraResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PairCameraResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PairCameraResponse) GetCamera() *ManagedCamera {
	if x != nil {
		return x.Camera
	}
	return nil
}

// Request to sync a specific camera
type ForceSyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CameraId      string                 `protobuf:"bytes,1,opt,name=camera_id,json=cameraId,proto3" json:"camera_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForceSyncRequest) Reset() {
	*x = ForceSyncRequest{}
	mi := &file_gopro_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForceSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForceSyncRequest) ProtoMessage() {}

func (x *ForceSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gopro_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForceSyncRequest.ProtoReflect.Descriptor instead.
func (*ForceSyncRequest) Descriptor() ([]byte, []int) {
	return file_gopro_proto_rawDescGZIP(), []int{20}
}

func (x *ForceSyncRequest) GetCameraId() string {
	if x != nil {
		return x.CameraId
	}
	return ""
}

// Response for force sync request
type ForceSyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	QueueEntry    *SyncQueueEntry        `protobuf:"bytes,3,opt,name=queue_entry,json=queueEntry,proto3" json:"queue_entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForceSyncResponse) Reset() {
	*x = ForceSyncResponse{}
	mi := &file_gopro_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForceSyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForceSyncResponse) ProtoMessage() {}

func (x *ForceSyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gopro_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForceSyncResponse.ProtoReflect.Descriptor instead.
func (*ForceSyncResponse) Descriptor() ([]byte, []int) {
	return file_gopro_proto_rawDescGZIP(), []int{21}
}

func (x *ForceSyncResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ForceSyncResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ForceSyncResponse) GetQueueEntry() *SyncQueueEntry {
	if x != nil {
		return x.QueueEntry
	}
	return nil
}

// Request to cancel sync for a specific camera
type CancelSyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CameraId      string                 `protobuf:"bytes,1,opt,name=camera_id,json=cameraId,proto3" json:"camera_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelSyncRequest) Reset() {
	*x = CancelSyncRequest{}
	mi := &file_gopro_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelSyncRequest) ProtoMessage() {}

func (x *CancelSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gopro_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelSyncRequest.ProtoReflect.Descriptor instead.
func (*CancelSyncRequest) Descriptor() ([]byte, []int) {
	return file_gopro_proto_rawDescGZIP(), []int{22}
}

func (x *CancelSyncRequest) GetCameraId() string {
	if x != nil {
		return x.CameraId
	}
	return ""
}

// Response for cancel sync request
type CancelSyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelSyncResponse) Reset() {
	*x = CancelSyncResponse{}
	mi := &file_gopro_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelSyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelSyncResponse) ProtoMessage() {}

func (x *CancelSyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gopro_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelSyncResponse.ProtoReflect.Descriptor instead.
func (*CancelSyncResponse) Descriptor() ([]byte, []int) {
	return file_gopro_proto_rawDescGZIP(), []int{23}
}

func (x *CancelSyncResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelSyncResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Group related requests and responses
type GetGroupsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupsRequest) Reset() {
	*x = GetGroupsRequest{}
	mi := &file_gopro_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupsRequest) ProtoMessage() {}

func (x *GetGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gopro_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupsRequest.ProtoReflect.Descriptor instead.
func (*GetGroupsRequest) Descriptor() ([]byte, []int) {
	return file_gopro_proto_rawDescGZIP(), []int{24}
}

type GetGroupsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Groups        []*Group               `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupsResponse) Reset() {
	*x = GetGroupsResponse{}
	mi := &file_gopro_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupsResponse) ProtoMessage() {}

func (x *GetGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gopro_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupsResponse.ProtoReflect.Descriptor instead.
func (*GetGroupsResponse) Descriptor() ([]byte, []int) {
	return file_gopro_proto_rawDescGZIP(), []int{25}
}

func (x *GetGroupsResponse) GetGroups() []*Group {
	if x != nil {
		return x.Groups
	}
	return nil
}

type CreateGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CameraIds     []string               `protobuf:"bytes,2,rep,name=camera_ids,json=cameraIds,proto3" json:"camera_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGroupRequest) Reset() {
	*x = CreateGroupRequest{}
	mi := &file_gopro_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupRequest) ProtoMessage() {}

func (x *CreateGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gopro_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupRequest.ProtoReflect.Descriptor instead.
func (*CreateGroupRequest) Descriptor() ([]byte, []int) {
	return file_gopro_proto_rawDescGZIP(), []int{26}
}

func (x *CreateGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateGroupRequest) GetCameraIds() []string {
	if x != nil {
		return x.CameraIds
	}
	return nil
}

type UpdateGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CameraIds     []string               `protobuf:"bytes,3,rep,name=camera_ids,json=cameraIds,proto3" json:"camera_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGroupRequest) Reset() {
	*x = UpdateGroupRequest{}
	mi := &file_gopro_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGroupRequest) ProtoMessage() {}

func (x *UpdateGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gopro_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGroupRequest.ProtoReflect.Descriptor instead.
func (*UpdateGroupRequest) Descriptor() ([]byte, []int) {
	return file_gopro_proto_rawDescGZIP(), []int{27}
}

func (x *UpdateGroupRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *UpdateGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateGroupRequest) GetCameraIds() []string {
	if x != nil {
		return x.CameraIds
	}
	return nil
}

type DeleteGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGroupRequest) Reset() {
	*x = DeleteGroupRequest{}
	mi := &file_gopro_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGroupRequest) ProtoMessage() {}

func (x *DeleteGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gopro_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGroupRequest.ProtoReflect.Descriptor instead.
func (*DeleteGroupRequest) Descriptor() ([]byte, []int) {
	return file_gopro_proto_rawDescGZIP(), []int{28}
}

func (x *DeleteGroupRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type LoadGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadGroupRequest) Reset() {
	*x = LoadGroupRequest{}
	mi := &file_gopro_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadGroupRequest) ProtoMessage() {}

func (x *LoadGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gopro_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadGroupRequest.ProtoReflect.Descriptor instead.
func (*LoadGroupRequest) Descriptor() ([]byte, []int) {
	return file_gopro_proto_rawDescGZIP(), []int{29}
}

func (x *LoadGroupRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type LoadGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadGroupResponse) Reset() {
	*x = LoadGroupResponse{}
	mi := &file_gopro_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadGroupResponse) ProtoMessage() {}

func (x *LoadGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gopro_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadGroupResponse.ProtoReflect.Descriptor instead.
func (*LoadGroupResponse) Descriptor() ([]byte, []int) {
	return file_gopro_proto_rawDescGZIP(), []int{30}
}

func (x *LoadGroupResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LoadGroupResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SaveManagedAsGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveManagedAsGroupRequest) Reset() {
	*x = SaveManagedAsGroupRequest{}
	mi := &file_gopro_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveManagedAsGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveManagedAsGroupRequest) ProtoMessage() {}

func (x *SaveManagedAsGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gopro_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveManagedAsGroupRequest.ProtoReflect.Descriptor instead.
func (*SaveManagedAsGroupRequest) Descriptor() ([]byte, []int) {
	return file_gopro_proto_rawDescGZIP(), []int{31}
}

func (x *SaveManagedAsGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Camera settings, refreshed over BLE. Options list only what the camera
// reported as available: per-model support comes from the camera itself.
type SettingOption struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int64                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettingOption) Reset() {
	*x = SettingOption{}
	mi := &file_gopro_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettingOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettingOption) ProtoMessage() {}

func (x *SettingOption) ProtoReflect() protoreflect.Message {
	mi := &file_gopro_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettingOption.ProtoReflect.Descriptor instead.
func (*SettingOption) Descriptor() ([]byte, []int) {
	return file_gopro_proto_rawDescGZIP(), []int{32}
}

func (x *SettingOption) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *SettingOption) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CameraSetting struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Value         int64                  `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`
	ValueName     string                 `protobuf:"bytes,4,opt,name=value_name,json=valueName,proto3" json:"value_name,omitempty"`
	Options       []*SettingOption       `protobuf:"bytes,5,rep,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CameraSetting) Reset() {
	*x = CameraSetting{}
	mi := &file_gopro_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CameraSetting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CameraSetting) ProtoMessage() {}

func (x *CameraSetting) ProtoReflect() protoreflect.Message {
	mi := &file_gopro_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CameraSetting.ProtoReflect.Descriptor instead.
func (*CameraSetting) Descriptor() ([]byte, []int) {
	return file_gopro_proto_rawDescGZIP(), []int{33}
}

func (x *CameraSetting) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CameraSetting) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CameraSetting) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *CameraSetting) GetValueName() string {
	if x != nil {
		return x.ValueName
	}
	return ""
}

func (x *CameraSetting) GetOptions() []*SettingOption {
	if x != nil {
		return x.Options
	}
	return nil
}

type SettingChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Value         int64                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettingChange) Reset() {
	*x = SettingChange{}
	mi := &file_gopro_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettingChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettingChange) ProtoMessage() {}

func (x *SettingChange) ProtoReflect() protoreflect.Message {
	mi := &file_gopro_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettingChange.ProtoReflect.Descriptor instead.
func (*SettingChange) Descriptor() ([]byte, []int) {
	return file_gopro_proto_rawDescGZIP(), []int{34}
}

func (x *SettingChange) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SettingChange) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type SettingApplyResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"` // empty = applied
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettingApplyResult) Reset() {
	*x = SettingApplyResult{}
	mi := &file_gopro_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettingApplyResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettingApplyResult) ProtoMessage() {}

func (x *SettingApplyResult) ProtoReflect() protoreflect.Message {
	mi := &file_gopro_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettingApplyResult.ProtoReflect.Descriptor instead.
func (*SettingApplyResult) Descriptor() ([]byte, []int) {
	return file_gopro_proto_rawDescGZIP(), []int{35}
}

func (x *SettingApplyResult) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SettingApplyResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CameraSettingsResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CameraId      string                 `protobuf:"bytes,1,opt,name=camera_id,json=cameraId,proto3" json:"camera_id,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"` // whole-camera failure; empty otherwise
	Results       []*SettingApplyResult  `protobuf:"bytes,3,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CameraSettingsResult) Reset() {
	*x = CameraSettingsResult{}
	mi := &file_gopro_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CameraSettingsResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CameraSettingsResult) ProtoMessage() {}

func (x *CameraSettingsResult) ProtoReflect() protoreflect.Message {
	mi := &file_gopro_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CameraSettingsResult.ProtoReflect.Descriptor instead.
func (*CameraSettingsResult) Descriptor() ([]byte, []int) {
	return file_gopro_proto_rawDescGZIP(), []int{36}
}

func (x *CameraSettingsResult) GetCameraId() string {
	if x != nil {
		return x.CameraId
	}
	return ""
}

func (x *CameraSettingsResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CameraSettingsResult) GetResults() []*SettingApplyResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type GetCameraSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CameraId      string                 `protobuf:"bytes,1,opt,name=camera_id,json=cameraId,proto3" json:"camera_id,omitempty"`
	Refresh       bool                   `protobuf:"varint,2,opt,name=refresh,proto3" json:"refresh,omitempty"` // true = read from the camera over BLE
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCameraSettingsRequest) Reset() {
	*x = GetCameraSettingsRequest{}
	mi := &file_gopro_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCameraSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCameraSettingsRequest) ProtoMessage() {}

func (x *GetCameraSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gopro_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCameraSettingsRequest.ProtoReflect.Descriptor instead.
func (*GetCameraSettingsRequest) Descriptor() ([]byte, []int) {
	return file_gopro_proto_rawDescGZIP(), []int{37}
}

func (x *GetCameraSettingsRequest) GetCameraId() string {
	if x != nil {
		return x.CameraId
	}
	return ""
}

func (x *GetCameraSettingsRequest) GetRefresh() bool {
	if x != nil {
		return x.Refresh
	}
	return false
}

type GetCameraSettingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settings      []*CameraSetting       `protobuf:"bytes,1,rep,name=settings,proto3" json:"settings,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCameraSettingsResponse) Reset() {
	*x = GetCameraSettingsResponse{}
	mi := &file_gopro_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCameraSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCameraSettingsResponse) ProtoMessage() {}

func (x *GetCameraSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gopro_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCameraSettingsResponse.ProtoReflect.Descriptor instead.
func (*GetCameraSettingsResponse) Descriptor() ([]byte, []int) {
	return file_gopro_proto_rawDescGZIP(), []int{38}
}

func (x *GetCameraSettingsResponse) GetSettings() []*CameraSetting {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *GetCameraSettingsResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ApplyCameraSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CameraId      string                 `protobuf:"bytes,1,opt,name=camera_id,json=cameraId,proto3" json:"camera_id,omitempty"` // exactly one of camera_id / group_id
	GroupId       string                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Changes       []*SettingChange       `protobuf:"bytes,3,rep,name=changes,proto3" json:"changes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyCameraSettingsRequest) Reset() {
	*x = ApplyCameraSettingsRequest{}
	mi := &file_gopro_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyCameraSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyCameraSettingsRequest) ProtoMessage() {}

func (x *ApplyCameraSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gopro_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyCameraSettingsRequest.ProtoReflect.Descriptor instead.
func (*ApplyCameraSettingsRequest) Descriptor() ([]byte, []int) {
	return file_gopro_proto_rawDescGZIP(), []int{39}
}

func (x *ApplyCameraSettingsRequest) GetCameraId() string {
	if x != nil {
		return x.CameraId
	}
	return ""
}

func (x *ApplyCameraSettingsRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *ApplyCameraSettingsRequest) GetChanges() []*SettingChange {
	if x != nil {
		return x.Changes
	}
	return nil
}

type ApplyCameraSettingsResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Cameras       []*CameraSettingsResult `protobuf:"bytes,1,rep,name=cameras,proto3" json:"cameras,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyCameraSettingsResponse) Reset() {
	*x = ApplyCameraSettingsResponse{}
	mi := &file_gopro_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyCameraSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyCameraSettingsResponse) ProtoMessage() {}

func (x *ApplyCameraSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gopro_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyCameraSettingsResponse.ProtoReflect.Descriptor instead.
func (*ApplyCameraSettingsResponse) Descriptor() ([]byte, []int) {
	return file_gopro_proto_rawDescGZIP(), []int{40}
}

func (x *ApplyCameraSettingsResponse) GetCameras() []*CameraSettingsResult {
	if x != nil {
		return x.Cameras
	}
	return nil
}

// Media browser: cached catalog of what is on a camera, captured at sync.
type CameraMediaItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CameraPath    string                 `protobuf:"bytes,2,opt,name=camera_path,json=cameraPath,proto3" json:"camera_path,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ThumbnailPath string                 `protobuf:"bytes,5,opt,name=thumbnail_path,json=thumbnailPath,proto3" json:"thumbnail_path,omitempty"` // absolute local path, empty if not cached
	Downloaded    bool                   `protobuf:"varint,6,opt,name=downloaded,proto3" json:"downloaded,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CameraMediaItem) Reset() {
	*x = CameraMediaItem{}
	mi := &file_gopro_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CameraMediaItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CameraMediaItem) ProtoMessage() {}

func (x *CameraMediaItem) ProtoReflect() protoreflect.Message {
	mi := &file_gopro_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CameraMediaItem.ProtoReflect.Descriptor instead.
func (*CameraMediaItem) Descriptor() ([]byte, []int) {
	return file_gopro_proto_rawDescGZIP(), []int{41}
}

func (x *CameraMediaItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CameraMediaItem) GetCameraPath() string {
	if x != nil {
		return x.CameraPath
	}
	return ""
}

func (x *CameraMediaItem) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *CameraMediaItem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *CameraMediaItem) GetThumbnailPath() string {
	if x != nil {
		return x.ThumbnailPath
	}
	return ""
}

func (x *CameraMediaItem) GetDownloaded() bool {
	if x != nil {
		return x.Downloaded
	}
	return false
}

type GetCameraMediaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CameraId      string                 `protobuf:"bytes,1,opt,name=camera_id,json=cameraId,proto3" json:"camera_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCameraMediaRequest) Reset() {
	*x = GetCameraMediaRequest{}
	mi := &file_gopro_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCameraMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCameraMediaRequest) ProtoMessage() {}

func (x *GetCameraMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gopro_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCameraMediaRequest.ProtoReflect.Descriptor instead.
func (*GetCameraMediaRequest) Descriptor() ([]byte, []int) {
	return file_gopro_proto_rawDescGZIP(), []int{42}
}

func (x *GetCameraMediaRequest) GetCameraId() string {
	if x != nil {
		return x.CameraId
	}
	return ""
}

type GetCameraMediaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*CameraMediaItem     `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // when the catalog was captured
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCameraMediaResponse) Reset() {
	*x = GetCameraMediaResponse{}
	mi := &file_gopro_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCameraMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCameraMediaResponse) ProtoMessage() {}

func (x *GetCameraMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gopro_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCameraMediaResponse.ProtoReflect.Descriptor instead.
func (*GetCameraMediaResponse) Descriptor() ([]byte, []int) {
	return file_gopro_proto_rawDescGZIP(), []int{43}
}

func (x *GetCameraMediaResponse) GetItems() []*CameraMediaItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetCameraMediaResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type RequestMediaDownloadRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	CameraId string                 `protobuf:"bytes,1,opt,name=camera_id,json=cameraId,proto3" json:"camera_id,omitempty"`
	// Empty = refresh the catalog and thumbnails without downloading.
	FileNames     []string `protobuf:"bytes,2,rep,name=file_names,json=fileNames,proto3" json:"file_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestMediaDownloadRequest) Reset() {
	*x = RequestMediaDownloadRequest{}
	mi := &file_gopro_proto_msgTypes[44]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestMediaDownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestMediaDownloadRequest) ProtoMessage() {}

func (x *RequestMediaDownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gopro_proto_msgTypes[44]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestMediaDownloadRequest.ProtoReflect.Descriptor instead.
func (*RequestMediaDownloadRequest) Descriptor() ([]byte, []int) {
	return file_gopro_proto_rawDescGZIP(), []int{44}
}

func (x *RequestMediaDownloadRequest) GetCameraId() string {
	if x != nil {
		return x.CameraId
	}
	return ""
}

func (x *RequestMediaDownloadRequest) GetFileNames() []string {
	if x != nil {
		return x.FileNames
	}
	return nil
}

type RequestMediaDownloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         *SyncQueueEntry        `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestMediaDownloadResponse) Reset() {
	*x = RequestMediaDownloadResponse{}
	mi := &file_gopro_proto_msgTypes[45]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestMediaDownloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestMediaDownloadResponse) ProtoMessage() {}

func (x *RequestMediaDownloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gopro_proto_msgTypes[45]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestMediaDownloadResponse.ProtoReflect.Descriptor instead.
func (*RequestMediaDownloadResponse) Descriptor() ([]byte, []int) {
	return file_gopro_proto_rawDescGZIP(), []int{45}
}

func (x *RequestMediaDownloadResponse) GetEntry() *SyncQueueEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

var File_gopro_proto protoreflect.FileDescriptor

const file_gopro_proto_rawDesc = "" +
	"\n" +
	"\vgopro.proto\x12\x05dropz\x1a\fcommon.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb9\x01\n" +
	"\x06Camera\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05alias\x18\x03 \x01(\tR\x05alias\x12\x1f\n" +
	"\vble_address\x18\x04 \x01(\tR\n" +
	"bleAddress\x12\x1b\n" +
	"\twifi_ssid\x18\x05 \x01(\tR\bwifiSsid\x12#\n" +
	"\rwifi_password\x18\x06 \x01(\tR\fwifiPassword\x12\x12\n" +
	"\x04rssi\x18\a \x01(\x05R\x04rssi\"\x8e\x03\n" +
	"\fCameraStatus\x127\n" +
	"\tlast_seen\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\x12;\n" +
	"\vlast_synced\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastSynced\x12\x1d\n" +
	"\n" +
	"is_pairing\x18\x03 \x01(\bR\tisPairing\x12\x1b\n" +
	"\tis_paired\x18\x04 \x01(\bR\bisPaired\x12\x1d\n" +
	"\n" +
	"is_managed\x18\x05 \x01(\bR\tisManaged\x12!\n" +
	"\fis_reachable\x18\x06 \x01(\bR\visReachable\x12\x1b\n" +
	"\tis_synced\x18\a \x01(\bR\bisSynced\x12\x1d\n" +
	"\n" +
	"is_syncing\x18\b \x01(\bR\tisSyncing\x12&\n" +
	"\x0flast_sync_error\x18\t \x01(\tR\rlastSyncError\x12&\n" +
	"\x0fin_pairing_mode\x18\n" +
	" \x01(\bR\rinPairingMode\"\xe8\x02\n" +
	"\x0eCameraMetadata\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12)\n" +
	"\x10firmware_version\x18\x02 \x01(\tR\x0ffirmwareVersion\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12#\n" +
	"\rserial_number\x18\x04 \x01(\tR\fserialNumber\x12#\n" +
	"\rbattery_level\x18\x05 \x01(\x05R\fbatteryLevel\x12)\n" +
	"\x10hardware_version\x18\a \x01(\tR\x0fhardwareVersion\x12\x1d\n" +
	"\n" +
	"num_photos\x18\b \x01(\x05R\tnumPhotos\x12\x1d\n" +
	"\n" +
	"num_videos\x18\t \x01(\x05R\tnumVideos\x12$\n" +
	"\x0esd_card_status\x18\n" +
	" \x01(\x05R\fsdCardStatus\x12,\n" +
	"\x12remaining_space_kb\x18\v \x01(\x03R\x10remainingSpaceKb\"\xb3\x01\n" +
	"\x0fCameraWithState\x12%\n" +
	"\x06camera\x18\x01 \x01(\v2\r.dropz.CameraR\x06camera\x12+\n" +
	"\x06status\x18\x02 \x01(\v2\x13.dropz.CameraStatusR\x06status\x12\x19\n" +
	"\bgroup_id\x18\x03 \x01(\tR\agroupId\x121\n" +
	"\bmetadata\x18\x04 \x01(\v2\x15.dropz.CameraMetadataR\bmetadata\"M\n" +
	"\x10DiscoveredCamera\x129\n" +
	"\fcamera_state\x18\x01 \x01(\v2\x16.dropz.CameraWithStateR\vcameraState\"J\n" +
	"\rManagedCamera\x129\n" +
	"\fcamera_state\x18\x01 \x01(\v2\x16.dropz.CameraWithStateR\vcameraState\"\xda\x01\n" +
	"\x0eSyncQueueEntry\x12\x1b\n" +
	"\tcamera_id\x18\x01 \x01(\tR\bcameraId\x127\n" +
	"\tqueued_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bqueuedAt\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\x05R\bpriority\x12)\n" +
	"\x10progress_percent\x18\x04 \x01(\x05R\x0fprogressPercent\x12+\n" +
	"\x11current_operation\x18\x05 \x01(\tR\x10currentOperation\"\xc0\x01\n" +
	"\x05Group\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"camera_ids\x18\x03 \x03(\tR\tcameraIds\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"D\n" +
	"\x1bGetDiscoveredCamerasRequest\x12%\n" +
	"\x0echange_counter\x18\x01 \x01(\x03R\rchangeCounter\"\xb5\x01\n" +
	"\x1cGetDiscoveredCamerasResponse\x121\n" +
	"\acameras\x18\x01 \x03(\v2\x17.dropz.DiscoveredCameraR\acameras\x12%\n" +
	"\x0echange_counter\x18\x02 \x01(\x03R\rchangeCounter\x12\x1d\n" +
	"\n" +
	"no_changes\x18\x03 \x01(\bR\tnoChanges\x12\x1c\n" +
	"\theartbeat\x18\x04 \x01(\bR\theartbeat\"A\n" +
	"\x18GetManagedCamerasRequest\x12%\n" +
	"\x0echange_counter\x18\x01 \x01(\x03R\rchangeCounter\"\xaf\x01\n" +
	"\x19GetManagedCamerasResponse\x12.\n" +
	"\acameras\x18\x01 \x03(\v2\x14.dropz.ManagedCameraR\acameras\x12%\n" +
	"\x0echange_counter\x18\x02 \x01(\x03R\rchangeCounter\x12\x1d\n" +
	"\n" +
	"no_changes\x18\x03 \x01(\bR\tnoChanges\x12\x1c\n" +
	"\theartbeat\x18\x04 \x01(\bR\theartbeat\"<\n" +
	"\x13GetSyncQueueRequest\x12%\n" +
	"\x0echange_counter\x18\x01 \x01(\x03R\rchangeCounter\"\xa7\x01\n" +
	"\x14GetSyncQueueResponse\x12+\n" +
	"\x05queue\x18\x01 \x03(\v2\x15.dropz.SyncQueueEntryR\x05queue\x12%\n" +
	"\x0echange_counter\x18\x02 \x01(\x03R\rchangeCounter\x12\x1d\n" +
	"\n" +
	"no_changes\x18\x03 \x01(\bR\tnoChanges\x12\x1c\n" +
	"\theartbeat\x18\x04 \x01(\bR\theartbeat\"2\n" +
	"\x13ManageCameraRequest\x12\x1b\n" +
	"\tcamera_id\x18\x01 \x01(\tR\bcameraId\"x\n" +
	"\x14ManageCameraResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12,\n" +
	"\x06camera\x18\x03 \x01(\v2\x14.dropz.ManagedCameraR\x06camera\"4\n" +
	"\x15UnmanageCameraRequest\x12\x1b\n" +
	"\tcamera_id\x18\x01 \x01(\tR\bcameraId\"L\n" +
	"\x16UnmanageCameraResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"0\n" +
	"\x11PairCameraRequest\x12\x1b\n" +
	"\tcamera_id\x18\x01 \x01(\tR\bcameraId\"v\n" +
	"\x12PairCameraResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12,\n" +
	"\x06camera\x18\x03 \x01(\v2\x14.dropz.ManagedCameraR\x06camera\"/\n" +
	"\x10ForceSyncRequest\x12\x1b\n" +
	"\tcamera_id\x18\x01 \x01(\tR\bcameraId\"\x7f\n" +
	"\x11ForceSyncResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x126\n" +
	"\vqueue_entry\x18\x03 \x01(\v2\x15.dropz.SyncQueueEntryR\n" +
	"queueEntry\"0\n" +
	"\x11CancelSyncRequest\x12\x1b\n" +
	"\tcamera_id\x18\x01 \x01(\tR\bcameraId\"H\n" +
	"\x12CancelSyncResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x12\n" +
	"\x10GetGroupsRequest\"9\n" +
	"\x11GetGroupsResponse\x12$\n" +
	"\x06groups\x18\x01 \x03(\v2\f.dropz.GroupR\x06groups\"G\n" +
	"\x12CreateGroupRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"camera_ids\x18\x02 \x03(\tR\tcameraIds\"b\n" +
	"\x12UpdateGroupRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"camera_ids\x18\x03 \x03(\tR\tcameraIds\"/\n" +
	"\x12DeleteGroupRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\"-\n" +
	"\x10LoadGroupRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\"G\n" +
	"\x11LoadGroupResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"/\n" +
	"\x19SaveManagedAsGroupRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"9\n" +
	"\rSettingOption\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x03R\x05value\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x98\x01\n" +
	"\rCameraSetting\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x03R\x05value\x12\x1d\n" +
	"\n" +
	"value_name\x18\x04 \x01(\tR\tvalueName\x12.\n" +
	"\aoptions\x18\x05 \x03(\v2\x14.dropz.SettingOptionR\aoptions\"5\n" +
	"\rSettingChange\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value\":\n" +
	"\x12SettingApplyResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"~\n" +
	"\x14CameraSettingsResult\x12\x1b\n" +
	"\tcamera_id\x18\x01 \x01(\tR\bcameraId\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x123\n" +
	"\aresults\x18\x03 \x03(\v2\x19.dropz.SettingApplyResultR\aresults\"Q\n" +
	"\x18GetCameraSettingsRequest\x12\x1b\n" +
	"\tcamera_id\x18\x01 \x01(\tR\bcameraId\x12\x18\n" +
	"\arefresh\x18\x02 \x01(\bR\arefresh\"\x88\x01\n" +
	"\x19GetCameraSettingsResponse\x120\n" +
	"\bsettings\x18\x01 \x03(\v2\x14.dropz.CameraSettingR\bsettings\x129\n" +
	"\n" +
	"updated_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x84\x01\n" +
	"\x1aApplyCameraSettingsRequest\x12\x1b\n" +
	"\tcamera_id\x18\x01 \x01(\tR\bcameraId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\x12.\n" +
	"\achanges\x18\x03 \x03(\v2\x14.dropz.SettingChangeR\achanges\"T\n" +
	"\x1bApplyCameraSettingsResponse\x125\n" +
	"\acameras\x18\x01 \x03(\v2\x1b.dropz.CameraSettingsResultR\acameras\"\xe7\x01\n" +
	"\x0fCameraMediaItem\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vcamera_path\x18\x02 \x01(\tR\n" +
	"cameraPath\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x03R\tsizeBytes\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12%\n" +
	"\x0ethumbnail_path\x18\x05 \x01(\tR\rthumbnailPath\x12\x1e\n" +
	"\n" +
	"downloaded\x18\x06 \x01(\bR\n" +
	"downloaded\"4\n" +
	"\x15GetCameraMediaRequest\x12\x1b\n" +
	"\tcamera_id\x18\x01 \x01(\tR\bcameraId\"\x81\x01\n" +
	"\x16GetCameraMediaResponse\x12,\n" +
	"\x05items\x18\x01 \x03(\v2\x16.dropz.CameraMediaItemR\x05items\x129\n" +
	"\n" +
	"updated_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"Y\n" +
	"\x1bRequestMediaDownloadRequest\x12\x1b\n" +
	"\tcamera_id\x18\x01 \x01(\tR\bcameraId\x12\x1d\n" +
	"\n" +
	"file_names\x18\x02 \x03(\tR\tfileNames\"K\n" +
	"\x1cRequestMediaDownloadResponse\x12+\n" +
	"\x05entry\x18\x01 \x01(\v2\x15.dropz.SyncQueueEntryR\x05entryB*Z(github.com/dropz/dropz/internal/protocolb\x06proto3"

var (
	file_gopro_proto_rawDescOnce sync.Once
	file_gopro_proto_rawDescData []byte
)

func file_gopro_proto_rawDescGZIP() []byte {
	file_gopro_proto_rawDescOnce.Do(func() {
		file_gopro_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gopro_proto_rawDesc), len(file_gopro_proto_rawDesc)))
	})
	return file_gopro_proto_rawDescData
}

var file_gopro_proto_msgTypes = make([]protoimpl.MessageInfo, 46)
var file_gopro_proto_goTypes = []any{
	(*Camera)(nil),                       // 0: dropz.Camera
	(*CameraStatus)(nil),                 // 1: dropz.CameraStatus
	(*CameraMetadata)(nil),               // 2: dropz.CameraMetadata
	(*CameraWithState)(nil),              // 3: dropz.CameraWithState
	(*DiscoveredCamera)(nil),             // 4: dropz.DiscoveredCamera
	(*ManagedCamera)(nil),                // 5: dropz.ManagedCamera
	(*SyncQueueEntry)(nil),               // 6: dropz.SyncQueueEntry
	(*Group)(nil),                        // 7: dropz.Group
	(*GetDiscoveredCamerasRequest)(nil),  // 8: dropz.GetDiscoveredCamerasRequest
	(*GetDiscoveredCamerasResponse)(nil), // 9: dropz.GetDiscoveredCamerasResponse
	(*GetManagedCamerasRequest)(nil),     // 10: dropz.GetManagedCamerasRequest
	(*GetManagedCamerasResponse)(nil),    // 11: dropz.GetManagedCamerasResponse
	(*GetSyncQueueRequest)(nil),          // 12: dropz.GetSyncQueueRequest
	(*GetSyncQueueResponse)(nil),         // 13: dropz.GetSyncQueueResponse
	(*ManageCameraRequest)(nil),          // 14: dropz.ManageCameraRequest
	(*ManageCameraResponse)(nil),         // 15: dropz.ManageCameraResponse
	(*UnmanageCameraRequest)(nil),        // 16: dropz.UnmanageCameraRequest
	(*UnmanageCameraResponse)(nil),       // 17: dropz.UnmanageCameraResponse
	(*PairCameraRequest)(nil),            // 18: dropz.PairCameraRequest
	(*PairCameraResponse)(nil),           // 19: dropz.PairCameraResponse
	(*ForceSyncRequest)(nil),             // 20: dropz.ForceSyncRequest
	(*ForceSyncResponse)(nil),            // 21: dropz.ForceSyncResponse
	(*CancelSyncRequest)(nil),            // 22: dropz.CancelSyncRequest
	(*CancelSyncResponse)(nil),           // 23: dropz.CancelSyncResponse
	(*GetGroupsRequest)(nil),             // 24: dropz.GetGroupsRequest
	(*GetGroupsResponse)(nil),            // 25: dropz.GetGroupsResponse
	(*CreateGroupRequest)(nil),           // 26: dropz.CreateGroupRequest
	(*UpdateGroupRequest)(nil),           // 27: dropz.UpdateGroupRequest
	(*DeleteGroupRequest)(nil),           // 28: dropz.DeleteGroupRequest
	(*LoadGroupRequest)(nil),             // 29: dropz.LoadGroupRequest
	(*LoadGroupResponse)(nil),            // 30: dropz.LoadGroupResponse
	(*SaveManagedAsGroupRequest)(nil),    // 31: dropz.SaveManagedAsGroupRequest
	(*SettingOption)(nil),                // 32: dropz.SettingOption
	(*CameraSetting)(nil),                // 33: dropz.CameraSetting
	(*SettingChange)(nil),                // 34: dropz.SettingChange
	(*SettingApplyResult)(nil),           // 35: dropz.SettingApplyResult
	(*CameraSettingsResult)(nil),         // 36: dropz.CameraSettingsResult
	(*GetCameraSettingsRequest)(nil),     // 37: dropz.GetCameraSettingsRequest
	(*GetCameraSettingsResponse)(nil),    // 38: dropz.GetCameraSettingsResponse
	(*ApplyCameraSettingsRequest)(nil),   // 39: dropz.ApplyCameraSettingsRequest
	(*ApplyCameraSettingsResponse)(nil),  // 40: dropz.ApplyCameraSettingsResponse
	(*CameraMediaItem)(nil),              // 41: dropz.CameraMediaItem
	(*GetCameraMediaRequest)(nil),        // 42: dropz.GetCameraMediaRequest
	(*GetCameraMediaResponse)(nil),       // 43: dropz.GetCameraMediaResponse
	(*RequestMediaDownloadRequest)(nil),  // 44: dropz.RequestMediaDownloadRequest
	(*RequestMediaDownloadResponse)(nil), // 45: dropz.RequestMediaDownloadResponse
	(*timestamppb.Timestamp)(nil),        // 46: google.protobuf.Timestamp
}
var file_gopro_proto_depIdxs = []int32{
	46, // 0: dropz.CameraStatus.last_seen:type_name -> google.protobuf.Timestamp
	46, // 1: dropz.CameraStatus.last_synced:type_name -> google.protobuf.Timestamp
	0,  // 2: dropz.CameraWithState.camera:type_name -> dropz.Camera
	1,  // 3: dropz.CameraWithState.status:type_name -> dropz.CameraStatus
	2,  // 4: dropz.CameraWithState.metadata:type_name -> dropz.CameraMetadata
	3,  // 5: dropz.DiscoveredCamera.camera_state:type_name -> dropz.CameraWithState
	3,  // 6: dropz.ManagedCamera.camera_state:type_name -> dropz.CameraWithState
	46, // 7: dropz.SyncQueueEntry.queued_at:type_name -> google.protobuf.Timestamp
	46, // 8: dropz.Group.created_at:type_name -> google.protobuf.Timestamp
	46, // 9: dropz.Group.updated_at:type_name -> google.protobuf.Timestamp
	4,  // 10: dropz.GetDiscoveredCamerasResponse.cameras:type_name -> dropz.DiscoveredCamera
	5,  // 11: dropz.GetManagedCamerasResponse.cameras:type_name -> dropz.ManagedCamera
	6,  // 12: dropz.GetSyncQueueResponse.queue:type_name -> dropz.SyncQueueEntry
	5,  // 13: dropz.ManageCameraResponse.camera:type_name -> dropz.ManagedCamera
	5,  // 14: dropz.PairCameraResponse.camera:type_name -> dropz.ManagedCamera
	6,  // 15: dropz.ForceSyncResponse.queue_entry:type_name -> dropz.SyncQueueEntry
	7,  // 16: dropz.GetGroupsResponse.groups:type_name -> dropz.Group
	32, // 17: dropz.CameraSetting.options:type_name -> dropz.SettingOption
	35, // 18: dropz.CameraSettingsResult.results:type_name -> dropz.SettingApplyResult
	33, // 19: dropz.GetCameraSettingsResponse.settings:type_name -> dropz.CameraSetting
	46, // 20: dropz.GetCameraSettingsResponse.updated_at:type_name -> google.protobuf.Timestamp
	34, // 21: dropz.ApplyCameraSettingsRequest.changes:type_name -> dropz.SettingChange
	36, // 22: dropz.ApplyCameraSettingsResponse.cameras:type_name -> dropz.CameraSettingsResult
	46, // 23: dropz.CameraMediaItem.created_at:type_name -> google.protobuf.Timestamp
	41, // 24: dropz.GetCameraMediaResponse.items:type_name -> dropz.CameraMediaItem
	46, // 25: dropz.GetCameraMediaResponse.updated_at:type_name -> google.protobuf.Timestamp
	6,  // 26: dropz.RequestMediaDownloadResponse.entry:type_name -> dropz.SyncQueueEntry
	27, // [27:27] is the sub-list for method output_type
	27, // [27:27] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_gopro_proto_init() }
func file_gopro_proto_init() {
	if File_gopro_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gopro_proto_rawDesc), len(file_gopro_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   46,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gopro_proto_goTypes,
		DependencyIndexes: file_gopro_proto_depIdxs,
		MessageInfos:      file_gopro_proto_msgTypes,
	}.Build()
	File_gopro_proto = out.File
	file_gopro_proto_goTypes = nil
	file_gopro_proto_depIdxs = nil
}
