// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: service.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\x05dropz\x1a\vgopro.proto\x1a\vvideo.proto\x1a\fconfig.proto\x1a\fcommon.proto2\xfa\f\n" +
	"\fDropzService\x12_\n" +
	"\x14GetDiscoveredCameras\x12\".dropz.GetDiscoveredCamerasRequest\x1a#.dropz.GetDiscoveredCamerasResponse\x12c\n" +
	"\x16WatchDiscoveredCameras\x12\".dropz.GetDiscoveredCamerasRequest\x1a#.dropz.GetDiscoveredCamerasResponse0\x01\x12V\n" +
	"\x11GetManagedCameras\x12\x1f.dropz.GetManagedCamerasRequest\x1a .dropz.GetManagedCamerasResponse\x12Z\n" +
	"\x13WatchManagedCameras\x12\x1f.dropz.GetManagedCamerasRequest\x1a .dropz.GetManagedCamerasResponse0\x01\x12G\n" +
	"\fManageCamera\x12\x1a.dropz.ManageCameraRequest\x1a\x1b.dropz.ManageCameraResponse\x12M\n" +
	"\x0eUnmanageCamera\x12\x1c.dropz.UnmanageCameraRequest\x1a\x1d.dropz.UnmanageCameraResponse\x12A\n" +
	"\n" +
	"PairCamera\x12\x18.dropz.PairCameraRequest\x1a\x19.dropz.PairCameraResponse\x12G\n" +
	"\fGetSyncQueue\x12\x1a.dropz.GetSyncQueueRequest\x1a\x1b.dropz.GetSyncQueueResponse\x12K\n" +
	"\x0eWatchSyncQueue\x12\x1a.dropz.GetSyncQueueRequest\x1a\x1b.dropz.GetSyncQueueResponse0\x01\x12>\n" +
	"\tForceSync\x12\x17.dropz.ForceSyncRequest\x1a\x18.dropz.ForceSyncResponse\x12A\n" +
	"\n" +
	"CancelSync\x12\x18.dropz.CancelSyncRequest\x1a\x19.dropz.CancelSyncResponse\x12>\n" +
	"\tGetGroups\x12\x17.dropz.GetGroupsRequest\x1a\x18.dropz.GetGroupsResponse\x126\n" +
	"\vCreateGroup\x12\x19.dropz.CreateGroupRequest\x1a\f.dropz.Group\x126\n" +
	"\vUpdateGroup\x12\x19.dropz.UpdateGroupRequest\x1a\f.dropz.Group\x12B\n" +
	"\vDeleteGroup\x12\x19.dropz.DeleteGroupRequest\x1a\x18.dropz.OperationResponse\x12>\n" +
	"\tLoadGroup\x12\x17.dropz.LoadGroupRequest\x1a\x18.dropz.LoadGroupResponse\x12D\n" +
	"\x12SaveManagedAsGroup\x12 .dropz.SaveManagedAsGroupRequest\x1a\f.dropz.Group\x12>\n" +
	"\tGetVideos\x12\x17.dropz.GetVideosRequest\x1a\x18.dropz.GetVideosResponse\x12>\n" +
	"\tGetConfig\x12\x17.dropz.GetConfigRequest\x1a\x18.dropz.GetConfigResponse\x12G\n" +
	"\fUpdateConfig\x12\x1a.dropz.UpdateConfigRequest\x1a\x1b.dropz.UpdateConfigResponse\x12A\n" +
	"\n" +
	"GetSetting\x12\x18.dropz.GetSettingRequest\x1a\x19.dropz.GetSettingResponse\x12;\n" +
	"\rUpdateSetting\x12\x1b.dropz.UpdateSettingRequest\x1a\r.dropz.Config\x129\n" +
	"\fResetSetting\x12\x1a.dropz.ResetSettingRequest\x1a\r.dropz.ConfigB*Z(github.com/dropz/dropz/internal/protocolb\x06proto3"

var file_service_proto_goTypes = []any{
	(*GetDiscoveredCamerasRequest)(nil),  // 0: dropz.GetDiscoveredCamerasRequest
	(*GetManagedCamerasRequest)(nil),     // 1: dropz.GetManagedCamerasRequest
	(*ManageCameraRequest)(nil),          // 2: dropz.ManageCameraRequest
	(*UnmanageCameraRequest)(nil),        // 3: dropz.UnmanageCameraRequest
	(*PairCameraRequest)(nil),            // 4: dropz.PairCameraRequest
	(*GetSyncQueueRequest)(nil),          // 5: dropz.GetSyncQueueRequest
	(*ForceSyncRequest)(nil),             // 6: dropz.ForceSyncRequest
	(*CancelSyncRequest)(nil),            // 7: dropz.CancelSyncRequest
	(*GetGroupsRequest)(nil),             // 8: dropz.GetGroupsRequest
	(*CreateGroupRequest)(nil),           // 9: dropz.CreateGroupRequest
	(*UpdateGroupRequest)(nil),           // 10: dropz.UpdateGroupRequest
	(*DeleteGroupRequest)(nil),           // 11: dropz.DeleteGroupRequest
	(*LoadGroupRequest)(nil),             // 12: dropz.LoadGroupRequest
	(*SaveManagedAsGroupRequest)(nil),    // 13: dropz.SaveManagedAsGroupRequest
	(*GetVideosRequest)(nil),             // 14: dropz.GetVideosRequest
	(*GetConfigRequest)(nil),             // 15: dropz.GetConfigRequest
	(*UpdateConfigRequest)(nil),          // 16: dropz.UpdateConfigRequest
	(*GetSettingRequest)(nil),            // 17: dropz.GetSettingRequest
	(*UpdateSettingRequest)(nil),         // 18: dropz.UpdateSettingRequest
	(*ResetSettingRequest)(nil),          // 19: dropz.ResetSettingRequest
	(*GetDiscoveredCamerasResponse)(nil), // 20: dropz.GetDiscoveredCamerasResponse
	(*GetManagedCamerasResponse)(nil),    // 21: dropz.GetManagedCamerasResponse
	(*ManageCameraResponse)(nil),         // 22: dropz.ManageCameraResponse
	(*UnmanageCameraResponse)(nil),       // 23: dropz.UnmanageCameraResponse
	(*PairCameraResponse)(nil),           // 24: dropz.PairCameraResponse
	(*GetSyncQueueResponse)(nil),         // 25: dropz.GetSyncQueueResponse
	(*ForceSyncResponse)(nil),            // 26: dropz.ForceSyncResponse
	(*CancelSyncResponse)(nil),           // 27: dropz.CancelSyncResponse
	(*GetGroupsResponse)(nil),            // 28: dropz.GetGroupsResponse
	(*Group)(nil),                        // 29: dropz.Group
	(*OperationResponse)(nil),            // 30: dropz.OperationResponse
	(*LoadGroupResponse)(nil),            // 31: dropz.LoadGroupResponse
	(*GetVideosResponse)(nil),            // 32: dropz.GetVideosResponse
	(*GetConfigResponse)(nil),            // 33: dropz.GetConfigResponse
	(*UpdateConfigResponse)(nil),         // 34: dropz.UpdateConfigResponse
	(*GetSettingResponse)(nil),           // 35: dropz.GetSettingResponse
	(*Config)(nil),                       // 36: dropz.Config
}
var file_service_proto_depIdxs = []int32{
	0,  // 0: dropz.DropzService.GetDiscoveredCameras:input_type -> dropz.GetDiscoveredCamerasRequest
	0,  // 1: dropz.DropzService.WatchDiscoveredCameras:input_type -> dropz.GetDiscoveredCamerasRequest
	1,  // 2: dropz.DropzService.GetManagedCameras:input_type -> dropz.GetManagedCamerasRequest
	1,  // 3: dropz.DropzService.WatchManagedCameras:input_type -> dropz.GetManagedCamerasRequest
	2,  // 4: dropz.DropzService.ManageCamera:input_type -> dropz.ManageCameraRequest
	3,  // 5: dropz.DropzService.UnmanageCamera:input_type -> dropz.UnmanageCameraRequest
	4,  // 6: dropz.DropzService.PairCamera:input_type -> dropz.PairCameraRequest
	5,  // 7: dropz.DropzService.GetSyncQueue:input_type -> dropz.GetSyncQueueRequest
	5,  // 8: dropz.DropzService.WatchSyncQueue:input_type -> dropz.GetSyncQueueRequest
	6,  // 9: dropz.DropzService.ForceSync:input_type -> dropz.ForceSyncRequest
	7,  // 10: dropz.DropzService.CancelSync:input_type -> dropz.CancelSyncRequest
	8,  // 11: dropz.DropzService.GetGroups:input_type -> dropz.GetGroupsRequest
	9,  // 12: dropz.DropzService.CreateGroup:input_type -> dropz.CreateGroupRequest
	10, // 13: dropz.DropzService.UpdateGroup:input_type -> dropz.UpdateGroupRequest
	11, // 14: dropz.DropzService.DeleteGroup:input_type -> dropz.DeleteGroupRequest
	12, // 15: dropz.DropzService.LoadGroup:input_type -> dropz.LoadGroupRequest
	13, // 16: dropz.DropzService.SaveManagedAsGroup:input_type -> dropz.SaveManagedAsGroupRequest
	14, // 17: dropz.DropzService.GetVideos:input_type -> dropz.GetVideosRequest
	15, // 18: dropz.DropzService.GetConfig:input_type -> dropz.GetConfigRequest
	16, // 19: dropz.DropzService.UpdateConfig:input_type -> dropz.UpdateConfigRequest
	17, // 20: dropz.DropzService.GetSetting:input_type -> dropz.GetSettingRequest
	18, // 21: dropz.DropzService.UpdateSetting:input_type -> dropz.UpdateSettingRequest
	19, // 22: dropz.DropzService.ResetSetting:input_type -> dropz.ResetSettingRequest
	20, // 23: dropz.DropzService.GetDiscoveredCameras:output_type -> dropz.GetDiscoveredCamerasResponse
	20, // 24: dropz.DropzService.WatchDiscoveredCameras:output_type -> dropz.GetDiscoveredCamerasResponse
	21, // 25: dropz.DropzService.GetManagedCameras:output_type -> dropz.GetManagedCamerasResponse
	21, // 26: dropz.DropzService.WatchManagedCameras:output_type -> dropz.GetManagedCamerasResponse
	22, // 27: dropz.DropzService.ManageCamera:output_type -> dropz.ManageCameraResponse
	23, // 28: dropz.DropzService.UnmanageCamera:output_type -> dropz.UnmanageCameraResponse
	24, // 29: dropz.DropzService.PairCamera:output_type -> dropz.PairCameraResponse
	25, // 30: dropz.DropzService.GetSyncQueue:output_type -> dropz.GetSyncQueueResponse
	25, // 31: dropz.DropzService.WatchSyncQueue:output_type -> dropz.GetSyncQueueResponse
	26, // 32: dropz.DropzService.ForceSync:output_type -> dropz.ForceSyncResponse
	27, // 33: dropz.DropzService.CancelSync:output_type -> dropz.CancelSyncResponse
	28, // 34: dropz.DropzService.GetGroups:output_type -> dropz.GetGroupsResponse
	29, // 35: dropz.DropzService.CreateGroup:output_type -> dropz.Group
	29, // 36: dropz.DropzService.UpdateGroup:output_type -> dropz.Group
	30, // 37: dropz.DropzService.DeleteGroup:output_type -> dropz.OperationResponse
	31, // 38: dropz.DropzService.LoadGroup:output_type -> dropz.LoadGroupResponse
	29, // 39: dropz.DropzService.SaveManagedAsGroup:output_type -> dropz.Group
	32, // 40: dropz.DropzService.GetVideos:output_type -> dropz.GetVideosResponse
	33, // 41: dropz.DropzService.GetConfig:output_type -> dropz.GetConfigResponse
	34, // 42: dropz.DropzService.UpdateConfig:output_type -> dropz.UpdateConfigResponse
	35, // 43: dropz.DropzService.GetSetting:output_type -> dropz.GetSettingResponse
	36, // 44: dropz.DropzService.UpdateSetting:output_type -> dropz.Config
	36, // 45: dropz.DropzService.ResetSetting:output_type -> dropz.Config
	23, // [23:46] is the sub-list for method output_type
	0,  // [0:23] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	file_gopro_proto_init()
	file_video_proto_init()
	file_config_proto_init()
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
