// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: service.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\x05dropz\x1a\vgopro.proto\x1a\vvideo.proto\x1a\fconfig.proto\x1a\fcommon.proto2\xca\x11\n" +
	"\fDropzService\x12_\n" +
	"\x14GetDiscoveredCameras\x12\".dropz.GetDiscoveredCamerasRequest\x1a#.dropz.GetDiscoveredCamerasResponse\x12c\n" +
	"\x16WatchDiscoveredCameras\x12\".dropz.GetDiscoveredCamerasRequest\x1a#.dropz.GetDiscoveredCamerasResponse0\x01\x12V\n" +
	"\x11GetManagedCameras\x12\x1f.dropz.GetManagedCamerasRequest\x1a .dropz.GetManagedCamerasResponse\x12Z\n" +
	"\x13WatchManagedCameras\x12\x1f.dropz.GetManagedCamerasRequest\x1a .dropz.GetManagedCamerasResponse0\x01\x12G\n" +
	"\fManageCamera\x12\x1a.dropz.ManageCameraRequest\x1a\x1b.dropz.ManageCameraResponse\x12M\n" +
	"\x0eUnmanageCamera\x12\x1c.dropz.UnmanageCameraRequest\x1a\x1d.dropz.UnmanageCameraResponse\x12A\n" +
	"\n" +
	"PairCamera\x12\x18.dropz.PairCameraRequest\x1a\x19.dropz.PairCameraResponse\x12V\n" +
	"\x11GetCameraSettings\x12\x1f.dropz.GetCameraSettingsRequest\x1a .dropz.GetCameraSettingsResponse\x12\\\n" +
	"\x13ApplyCameraSettings\x12!.dropz.ApplyCameraSettingsRequest\x1a\".dropz.ApplyCameraSettingsResponse\x12G\n" +
	"\fGetSyncQueue\x12\x1a.dropz.GetSyncQueueRequest\x1a\x1b.dropz.GetSyncQueueResponse\x12K\n" +
	"\x0eWatchSyncQueue\x12\x1a.dropz.GetSyncQueueRequest\x1a\x1b.dropz.GetSyncQueueResponse0\x01\x12>\n" +
	"\tForceSync\x12\x17.dropz.ForceSyncRequest\x1a\x18.dropz.ForceSyncResponse\x12A\n" +
	"\n" +
	"CancelSync\x12\x18.dropz.CancelSyncRequest\x1a\x19.dropz.CancelSyncResponse\x12>\n" +
	"\tGetGroups\x12\x17.dropz.GetGroupsRequest\x1a\x18.dropz.GetGroupsResponse\x126\n" +
	"\vCreateGroup\x12\x19.dropz.CreateGroupRequest\x1a\f.dropz.Group\x126\n" +
	"\vUpdateGroup\x12\x19.dropz.UpdateGroupRequest\x1a\f.dropz.Group\x12B\n" +
	"\vDeleteGroup\x12\x19.dropz.DeleteGroupRequest\x1a\x18.dropz.OperationResponse\x12>\n" +
	"\tLoadGroup\x12\x17.dropz.LoadGroupRequest\x1a\x18.dropz.LoadGroupResponse\x12D\n" +
	"\x12SaveManagedAsGroup\x12 .dropz.SaveManagedAsGroupRequest\x1a\f.dropz.Group\x12>\n" +
	"\tGetVideos\x12\x17.dropz.GetVideosRequest\x1a\x18.dropz.GetVideosResponse\x12M\n" +
	"\x0eGetCameraMedia\x12\x1c.dropz.GetCameraMediaRequest\x1a\x1d.dropz.GetCameraMediaResponse\x12_\n" +
	"\x14RequestMediaDownload\x12\".dropz.RequestMediaDownloadRequest\x1a#.dropz.RequestMediaDownloadResponse\x12G\n" +
	"\fPreviewMedia\x12\x1a.dropz.PreviewMediaRequest\x1a\x1b.dropz.PreviewMediaResponse\x12G\n" +
	"\fPreviewVideo\x12\x1a.dropz.PreviewVideoRequest\x1a\x1b.dropz.PreviewVideoResponse\x12V\n" +
	"\x11SetPreviewSession\x12\x1f.dropz.SetPreviewSessionRequest\x1a .dropz.SetPreviewSessionResponse\x12>\n" +
	"\tGetConfig\x12\x17.dropz.GetConfigRequest\x1a\x18.dropz.GetConfigResponse\x12G\n" +
	"\fUpdateConfig\x12\x1a.dropz.UpdateConfigRequest\x1a\x1b.dropz.UpdateConfigResponse\x12A\n" +
	"\n" +
	"GetSetting\x12\x18.dropz.GetSettingRequest\x1a\x19.dropz.GetSettingResponse\x12;\n" +
	"\rUpdateSetting\x12\x1b.dropz.UpdateSettingRequest\x1a\r.dropz.Config\x129\n" +
	"\fResetSetting\x12\x1a.dropz.ResetSettingRequest\x1a\r.dropz.ConfigB*Z(github.com/dropz/dropz/internal/protocolb\x06proto3"

var file_service_proto_goTypes = []any{
	(*GetDiscoveredCamerasRequest)(nil),  // 0: dropz.GetDiscoveredCamerasRequest
	(*GetManagedCamerasRequest)(nil),     // 1: dropz.GetManagedCamerasRequest
	(*ManageCameraRequest)(nil),          // 2: dropz.ManageCameraRequest
	(*UnmanageCameraRequest)(nil),        // 3: dropz.UnmanageCameraRequest
	(*PairCameraRequest)(nil),            // 4: dropz.PairCameraRequest
	(*GetCameraSettingsRequest)(nil),     // 5: dropz.GetCameraSettingsRequest
	(*ApplyCameraSettingsRequest)(nil),   // 6: dropz.ApplyCameraSettingsRequest
	(*GetSyncQueueRequest)(nil),          // 7: dropz.GetSyncQueueRequest
	(*ForceSyncRequest)(nil),             // 8: dropz.ForceSyncRequest
	(*CancelSyncRequest)(nil),            // 9: dropz.CancelSyncRequest
	(*GetGroupsRequest)(nil),             // 10: dropz.GetGroupsRequest
	(*CreateGroupRequest)(nil),           // 11: dropz.CreateGroupRequest
	(*UpdateGroupRequest)(nil),           // 12: dropz.UpdateGroupRequest
	(*DeleteGroupRequest)(nil),           // 13: dropz.DeleteGroupRequest
	(*LoadGroupRequest)(nil),             // 14: dropz.LoadGroupRequest
	(*SaveManagedAsGroupRequest)(nil),    // 15: dropz.SaveManagedAsGroupRequest
	(*GetVideosRequest)(nil),             // 16: dropz.GetVideosRequest
	(*GetCameraMediaRequest)(nil),        // 17: dropz.GetCameraMediaRequest
	(*RequestMediaDownloadRequest)(nil),  // 18: dropz.RequestMediaDownloadRequest
	(*PreviewMediaRequest)(nil),          // 19: dropz.PreviewMediaRequest
	(*PreviewVideoRequest)(nil),          // 20: dropz.PreviewVideoRequest
	(*SetPreviewSessionRequest)(nil),     // 21: dropz.SetPreviewSessionRequest
	(*GetConfigRequest)(nil),             // 22: dropz.GetConfigRequest
	(*UpdateConfigRequest)(nil),          // 23: dropz.UpdateConfigRequest
	(*GetSettingRequest)(nil),            // 24: dropz.GetSettingRequest
	(*UpdateSettingRequest)(nil),         // 25: dropz.UpdateSettingRequest
	(*ResetSettingRequest)(nil),          // 26: dropz.ResetSettingRequest
	(*GetDiscoveredCamerasResponse)(nil), // 27: dropz.GetDiscoveredCamerasResponse
	(*GetManagedCamerasResponse)(nil),    // 28: dropz.GetManagedCamerasResponse
	(*ManageCameraResponse)(nil),         // 29: dropz.ManageCameraResponse
	(*UnmanageCameraResponse)(nil),       // 30: dropz.UnmanageCameraResponse
	(*PairCameraResponse)(nil),           // 31: dropz.PairCameraResponse
	(*GetCameraSettingsResponse)(nil),    // 32: dropz.GetCameraSettingsResponse
	(*ApplyCameraSettingsResponse)(nil),  // 33: dropz.ApplyCameraSettingsResponse
	(*GetSyncQueueResponse)(nil),         // 34: dropz.GetSyncQueueResponse
	(*ForceSyncResponse)(nil),            // 35: dropz.ForceSyncResponse
	(*CancelSyncResponse)(nil),           // 36: dropz.CancelSyncResponse
	(*GetGroupsResponse)(nil),            // 37: dropz.GetGroupsResponse
	(*Group)(nil),                        // 38: dropz.Group
	(*OperationResponse)(nil),            // 39: dropz.OperationResponse
	(*LoadGroupResponse)(nil),            // 40: dropz.LoadGroupResponse
	(*GetVideosResponse)(nil),            // 41: dropz.GetVideosResponse
	(*GetCameraMediaResponse)(nil),       // 42: dropz.GetCameraMediaResponse
	(*RequestMediaDownloadResponse)(nil), // 43: dropz.RequestMediaDownloadResponse
	(*PreviewMediaResponse)(nil),         // 44: dropz.PreviewMediaResponse
	(*PreviewVideoResponse)(nil),         // 45: dropz.PreviewVideoResponse
	(*SetPreviewSessionResponse)(nil),    // 46: dropz.SetPreviewSessionResponse
	(*GetConfigResponse)(nil),            // 47: dropz.GetConfigResponse
	(*UpdateConfigResponse)(nil),         // 48: dropz.UpdateConfigResponse
	(*GetSettingResponse)(nil),           // 49: dropz.GetSettingResponse
	(*Config)(nil),                       // 50: dropz.Config
}
var file_service_proto_depIdxs = []int32{
	0,  // 0: dropz.DropzService.GetDiscoveredCameras:input_type -> dropz.GetDiscoveredCamerasRequest
	0,  // 1: dropz.DropzService.WatchDiscoveredCameras:input_type -> dropz.GetDiscoveredCamerasRequest
	1,  // 2: dropz.DropzService.GetManagedCameras:input_type -> dropz.GetManagedCamerasRequest
	1,  // 3: dropz.DropzService.WatchManagedCameras:input_type -> dropz.GetManagedCamerasRequest
	2,  // 4: dropz.DropzService.ManageCamera:input_type -> dropz.ManageCameraRequest
	3,  // 5: dropz.DropzService.UnmanageCamera:input_type -> dropz.UnmanageCameraRequest
	4,  // 6: dropz.DropzService.PairCamera:input_type -> dropz.PairCameraRequest
	5,  // 7: dropz.DropzService.GetCameraSettings:input_type -> dropz.GetCameraSettingsRequest
	6,  // 8: dropz.DropzService.ApplyCameraSettings:input_type -> dropz.ApplyCameraSettingsRequest
	7,  // 9: dropz.DropzService.GetSyncQueue:input_type -> dropz.GetSyncQueueRequest
	7,  // 10: dropz.DropzService.WatchSyncQueue:input_type -> dropz.GetSyncQueueRequest
	8,  // 11: dropz.DropzService.ForceSync:input_type -> dropz.ForceSyncRequest
	9,  // 12: dropz.DropzService.CancelSync:input_type -> dropz.CancelSyncRequest
	10, // 13: dropz.DropzService.GetGroups:input_type -> dropz.GetGroupsRequest
	11, // 14: dropz.DropzService.CreateGroup:input_type -> dropz.CreateGroupRequest
	12, // 15: dropz.DropzService.UpdateGroup:input_type -> dropz.UpdateGroupRequest
	13, // 16: dropz.DropzService.DeleteGroup:input_type -> dropz.DeleteGroupRequest
	14, // 17: dropz.DropzService.LoadGroup:input_type -> dropz.LoadGroupRequest
	15, // 18: dropz.DropzService.SaveManagedAsGroup:input_type -> dropz.SaveManagedAsGroupRequest
	16, // 19: dropz.DropzService.GetVideos:input_type -> dropz.GetVideosRequest
	17, // 20: dropz.DropzService.GetCameraMedia:input_type -> dropz.GetCameraMediaRequest
	18, // 21: dropz.DropzService.RequestMediaDownload:input_type -> dropz.RequestMediaDownloadRequest
	19, // 22: dropz.DropzService.PreviewMedia:input_type -> dropz.PreviewMediaRequest
	20, // 23: dropz.DropzService.PreviewVideo:input_type -> dropz.PreviewVideoRequest
	21, // 24: dropz.DropzService.SetPreviewSession:input_type -> dropz.SetPreviewSessionRequest
	22, // 25: dropz.DropzService.GetConfig:input_type -> dropz.GetConfigRequest
	23, // 26: dropz.DropzService.UpdateConfig:input_type -> dropz.UpdateConfigRequest
	24, // 27: dropz.DropzService.GetSetting:input_type -> dropz.GetSettingRequest
	25, // 28: dropz.DropzService.UpdateSetting:input_type -> dropz.UpdateSettingRequest
	26, // 29: dropz.DropzService.ResetSetting:input_type -> dropz.ResetSettingRequest
	27, // 30: dropz.DropzService.GetDiscoveredCameras:output_type -> dropz.GetDiscoveredCamerasResponse
	27, // 31: dropz.DropzService.WatchDiscoveredCameras:output_type -> dropz.GetDiscoveredCamerasResponse
	28, // 32: dropz.DropzService.GetManagedCameras:output_type -> dropz.GetManagedCamerasResponse
	28, // 33: dropz.DropzService.WatchManagedCameras:output_type -> dropz.GetManagedCamerasResponse
	29, // 34: dropz.DropzService.ManageCamera:output_type -> dropz.ManageCameraResponse
	30, // 35: dropz.DropzService.UnmanageCamera:output_type -> dropz.UnmanageCameraResponse
	31, // 36: dropz.DropzService.PairCamera:output_type -> dropz.PairCameraResponse
	32, // 37: dropz.DropzService.GetCameraSettings:output_type -> dropz.GetCameraSettingsResponse
	33, // 38: dropz.DropzService.ApplyCameraSettings:output_type -> dropz.ApplyCameraSettingsResponse
	34, // 39: dropz.DropzService.GetSyncQueue:output_type -> dropz.GetSyncQueueResponse
	34, // 40: dropz.DropzService.WatchSyncQueue:output_type -> dropz.GetSyncQueueResponse
	35, // 41: dropz.DropzService.ForceSync:output_type -> dropz.ForceSyncResponse
	36, // 42: dropz.DropzService.CancelSync:output_type -> dropz.CancelSyncResponse
	37, // 43: dropz.DropzService.GetGroups:output_type -> dropz.GetGroupsResponse
	38, // 44: dropz.DropzService.CreateGroup:output_type -> dropz.Group
	38, // 45: dropz.DropzService.UpdateGroup:output_type -> dropz.Group
	39, // 46: dropz.DropzService.DeleteGroup:output_type -> dropz.OperationResponse
	40, // 47: dropz.DropzService.LoadGroup:output_type -> dropz.LoadGroupResponse
	38, // 48: dropz.DropzService.SaveManagedAsGroup:output_type -> dropz.Group
	41, // 49: dropz.DropzService.GetVideos:output_type -> dropz.GetVideosResponse
	42, // 50: dropz.DropzService.GetCameraMedia:output_type -> dropz.GetCameraMediaResponse
	43, // 51: dropz.DropzService.RequestMediaDownload:output_type -> dropz.RequestMediaDownloadResponse
	44, // 52: dropz.DropzService.PreviewMedia:output_type -> dropz.PreviewMediaResponse
	45, // 53: dropz.DropzService.PreviewVideo:output_type -> dropz.PreviewVideoResponse
	46, // 54: dropz.DropzService.SetPreviewSession:output_type -> dropz.SetPreviewSessionResponse
	47, // 55: dropz.DropzService.GetConfig:output_type -> dropz.GetConfigResponse
	48, // 56: dropz.DropzService.UpdateConfig:output_type -> dropz.UpdateConfigResponse
	49, // 57: dropz.DropzService.GetSetting:output_type -> dropz.GetSettingResponse
	50, // 58: dropz.DropzService.UpdateSetting:output_type -> dropz.Config
	50, // 59: dropz.DropzService.ResetSetting:output_type -> dropz.Config
	30, // [30:60] is the sub-list for method output_type
	0,  // [0:30] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	file_gopro_proto_init()
	file_video_proto_init()
	file_config_proto_init()
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
